# -*- coding: utf-8 -*-

"""Qt widget construction and responsive sizing for the PhreeFit main window.

This module intentionally contains no signal wiring, file I/O, or calculation logic.
"""

from dataclasses import dataclass

from PySide6.QtCore import QCoreApplication, QEvent, QMetaObject, QObject, QRect, QTimer, Qt
from PySide6.QtGui import QAction, QDoubleValidator, QFont, QIntValidator
from PySide6.QtWidgets import (
    QCheckBox, QComboBox, QGroupBox, QHeaderView, QLabel, QLineEdit, QMenu, QMenuBar,
    QPushButton, QRadioButton, QStackedWidget, QStatusBar, QTableView,
    QTextEdit, QVBoxLayout, QWidget,
)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(810, 608)
        self.actionDatabase_path = QAction(MainWindow)
        self.actionDatabase_path.setObjectName(u"actionDatabase_path")
        self.actionparameters = QAction(MainWindow)
        self.actionparameters.setObjectName(u"actionparameters")
        self.actionpp = QAction(MainWindow)
        self.actionpp.setObjectName(u"actionpp")
        self.actionTitration = QAction(MainWindow)
        self.actionTitration.setObjectName(u"actionTitration")
        font = QFont()
        font.setFamilies([u"Arial"])
        self.actionTitration.setFont(font)
        self.actionPlot = QAction(MainWindow)
        self.actionPlot.setObjectName(u"actionPlot")
        self.actionPlot.setFont(font)
        self.actionAdvanced = QAction(MainWindow)
        self.actionAdvanced.setObjectName(u"actionAdvanced")
        self.actionAdvanced.setFont(font)
        self.actiondifferential_evolution = QAction(MainWindow)
        self.actiondifferential_evolution.setObjectName(u"actiondifferential_evolution")
        self.actiondifferential_evolution.setCheckable(True)
        self.actiondifferential_evolution.setChecked(True)
        self.actiondifferential_evolution.setFont(font)
        self.actionDual_annealing = QAction(MainWindow)
        self.actionDual_annealing.setObjectName(u"actionDual_annealing")
        self.actionDual_annealing.setCheckable(True)
        self.actionDual_annealing.setFont(font)
        self.actionnelder_mead = QAction(MainWindow)
        self.actionnelder_mead.setObjectName(u"actionnelder_mead")
        self.actionnelder_mead.setCheckable(True)
        self.actionnelder_mead.setFont(font)
        self.actionDatabase_folder = QAction(MainWindow)
        self.actionDatabase_folder.setObjectName(u"actionDatabase_folder")
        self.actionDatabase_folder.setFont(font)
        self.actionOutput_folder = QAction(MainWindow)
        self.actionOutput_folder.setObjectName(u"actionOutput_folder")
        self.actionOutput_folder.setFont(font)
        self.actionDisabled = QAction(MainWindow)
        self.actionDisabled.setObjectName(u"actionDisabled")
        self.actionDisabled.setCheckable(True)
        self.actionDisabled.setChecked(True)
        self.actionDisabled.setFont(font)
        self.actionEnabled = QAction(MainWindow)
        self.actionEnabled.setObjectName(u"actionEnabled")
        self.actionEnabled.setCheckable(True)
        self.actionEnabled.setChecked(False)
        self.actionEnabled.setFont(font)
        self.actionData_folder = QAction(MainWindow)
        self.actionData_folder.setObjectName(u"actionData_folder")
        self.actionSave_settings = QAction(MainWindow)
        self.actionSave_settings.setObjectName(u"actionSave_settings")
        self.actionLoad_settings = QAction(MainWindow)
        self.actionLoad_settings.setObjectName(u"actionLoad_settings")
        self.actionCompare_results = QAction(MainWindow)
        self.actionCompare_results.setObjectName(u"actionCompare_results")
        self.actionOpen_output_folder = QAction(MainWindow)
        self.actionOpen_output_folder.setObjectName(u"actionOpen_output_folder")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 10, 801, 571))
        self.stackedWidget.setFont(font)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label_28 = QLabel(self.page)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(230, 330, 71, 21))
        self.label_27 = QLabel(self.page)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(230, 300, 71, 21))
        self.groupBox_2 = QGroupBox(self.page)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(220, 150, 231, 131))
        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(180, 60, 54, 12))
        self.radioButton_fx = QRadioButton(self.groupBox_2)
        self.radioButton_fx.setObjectName(u"radioButton_fx")
        self.radioButton_fx.setGeometry(QRect(100, 20, 89, 16))
        self.radioButton_ds = QRadioButton(self.groupBox_2)
        self.radioButton_ds.setObjectName(u"radioButton_ds")
        self.radioButton_ds.setGeometry(QRect(100, 40, 89, 16))
        self.lineEdit_base = QLineEdit(self.groupBox_2)
        self.lineEdit_base.setObjectName(u"lineEdit_base")
        self.lineEdit_base.setGeometry(QRect(90, 60, 81, 20))
        self.comboBox_bs = QComboBox(self.groupBox_2)
        self.comboBox_bs.addItem("")
        self.comboBox_bs.addItem("")
        self.comboBox_bs.setObjectName(u"comboBox_bs")
        self.comboBox_bs.setGeometry(QRect(10, 60, 69, 22))
        self.label_mix = QLabel(self.groupBox_2)
        self.label_mix.setObjectName(u"label_mix")
        self.label_mix.setGeometry(QRect(10, 20, 81, 21))
        self.comboBox_ad = QComboBox(self.groupBox_2)
        self.comboBox_ad.addItem("")
        self.comboBox_ad.addItem("")
        self.comboBox_ad.setObjectName(u"comboBox_ad")
        self.comboBox_ad.setGeometry(QRect(10, 90, 69, 22))
        self.lineEdit_acid = QLineEdit(self.groupBox_2)
        self.lineEdit_acid.setObjectName(u"lineEdit_acid")
        self.lineEdit_acid.setGeometry(QRect(90, 90, 81, 20))
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(180, 90, 54, 12))
        self.groupBox_3 = QGroupBox(self.page)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(220, 20, 231, 121))
        self.lineEdit_vol = QLineEdit(self.groupBox_3)
        self.lineEdit_vol.setObjectName(u"lineEdit_vol")
        self.lineEdit_vol.setGeometry(QRect(122, 80, 101, 20))
        self.label_cs = QLabel(self.groupBox_3)
        self.label_cs.setObjectName(u"label_cs")
        self.label_cs.setGeometry(QRect(20, 20, 71, 21))
        self.label_ph = QLabel(self.groupBox_3)
        self.label_ph.setObjectName(u"label_ph")
        self.label_ph.setGeometry(QRect(20, 50, 71, 21))
        self.label_vol = QLabel(self.groupBox_3)
        self.label_vol.setObjectName(u"label_vol")
        self.label_vol.setGeometry(QRect(10, 80, 101, 21))
        self.lineEdit_ph = QLineEdit(self.groupBox_3)
        self.lineEdit_ph.setObjectName(u"lineEdit_ph")
        self.lineEdit_ph.setGeometry(QRect(100, 50, 113, 20))
        self.lineEdit_cs = QLineEdit(self.groupBox_3)
        self.lineEdit_cs.setObjectName(u"lineEdit_cs")
        self.lineEdit_cs.setGeometry(QRect(100, 20, 113, 20))
        self.lineEdit_iter = QLineEdit(self.page)
        self.lineEdit_iter.setObjectName(u"lineEdit_iter")
        self.lineEdit_iter.setGeometry(QRect(290, 300, 61, 20))
        self.pushButton_db = QPushButton(self.page)
        self.pushButton_db.setObjectName(u"pushButton_db")
        self.pushButton_db.setGeometry(QRect(30, 10, 171, 51))
        self.groupBox_4 = QGroupBox(self.page)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(230, 450, 551, 101))
        self.textEdit_res = QTextEdit(self.groupBox_4)
        self.textEdit_res.setObjectName(u"textEdit_res")
        self.textEdit_res.setGeometry(QRect(0, 30, 551, 71))
        self.pushButton_rd = QPushButton(self.page)
        self.pushButton_rd.setObjectName(u"pushButton_rd")
        self.pushButton_rd.setGeometry(QRect(30, 60, 171, 51))
        self.lineEdit_temp = QLineEdit(self.page)
        self.lineEdit_temp.setObjectName(u"lineEdit_temp")
        self.lineEdit_temp.setGeometry(QRect(290, 330, 61, 20))
        self.pushButton_opt = QPushButton(self.page)
        self.pushButton_opt.setObjectName(u"pushButton_opt")
        self.pushButton_opt.setGeometry(QRect(370, 290, 81, 101))
        self.tableView = QTableView(self.page)
        self.tableView.setObjectName(u"tableView")
        self.tableView.setGeometry(QRect(10, 120, 201, 391))
        self.groupBox = QGroupBox(self.page)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(460, 20, 331, 421))
        self.textEdit_sf = QTextEdit(self.groupBox)
        self.textEdit_sf.setObjectName(u"textEdit_sf")
        self.textEdit_sf.setGeometry(QRect(0, 320, 331, 101))
        self.pushButton_addsf = QPushButton(self.groupBox)
        self.pushButton_addsf.setObjectName(u"pushButton_addsf")
        self.pushButton_addsf.setGeometry(QRect(10, 290, 111, 23))
        self.comboBox_mdl = QComboBox(self.groupBox)
        self.comboBox_mdl.addItem("")
        self.comboBox_mdl.addItem("")
        self.comboBox_mdl.addItem("")
        self.comboBox_mdl.setObjectName(u"comboBox_mdl")
        self.comboBox_mdl.setGeometry(QRect(110, 120, 69, 22))
        self.lineEdit_sarea = QLineEdit(self.groupBox)
        self.lineEdit_sarea.setObjectName(u"lineEdit_sarea")
        self.lineEdit_sarea.setGeometry(QRect(110, 60, 113, 20))
        self.lineEdit_sname = QLineEdit(self.groupBox)
        self.lineEdit_sname.setObjectName(u"lineEdit_sname")
        self.lineEdit_sname.setGeometry(QRect(110, 30, 113, 20))
        self.label_25 = QLabel(self.groupBox)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(20, 30, 81, 21))
        self.lineEdit_smass = QLineEdit(self.groupBox)
        self.lineEdit_smass.setObjectName(u"lineEdit_smass")
        self.lineEdit_smass.setGeometry(QRect(110, 90, 113, 20))
        self.label_26 = QLabel(self.groupBox)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(20, 60, 81, 21))
        self.label_29 = QLabel(self.groupBox)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(230, 60, 81, 21))
        self.label_30 = QLabel(self.groupBox)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(20, 90, 81, 21))
        self.label_31 = QLabel(self.groupBox)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(230, 90, 81, 21))
        self.label_32 = QLabel(self.groupBox)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(20, 120, 81, 21))
        self.pushButton_review = QPushButton(self.groupBox)
        self.pushButton_review.setObjectName(u"pushButton_review")
        self.pushButton_review.setGeometry(QRect(120, 290, 131, 23))
        self.label_33 = QLabel(self.groupBox)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(110, 150, 81, 21))
        self.label_34 = QLabel(self.groupBox)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(220, 150, 81, 21))
        self.checkBox_dpro = QCheckBox(self.groupBox)
        self.checkBox_dpro.setObjectName(u"checkBox_dpro")
        self.checkBox_dpro.setGeometry(QRect(20, 170, 91, 16))
        self.checkBox_pro = QCheckBox(self.groupBox)
        self.checkBox_pro.setObjectName(u"checkBox_pro")
        self.checkBox_pro.setGeometry(QRect(20, 200, 91, 16))
        self.lineEdit_ikdp = QLineEdit(self.groupBox)
        self.lineEdit_ikdp.setObjectName(u"lineEdit_ikdp")
        self.lineEdit_ikdp.setGeometry(QRect(120, 170, 51, 20))
        self.lineEdit_dplb = QLineEdit(self.groupBox)
        self.lineEdit_dplb.setObjectName(u"lineEdit_dplb")
        self.lineEdit_dplb.setGeometry(QRect(200, 170, 51, 20))
        self.lineEdit_dpub = QLineEdit(self.groupBox)
        self.lineEdit_dpub.setObjectName(u"lineEdit_dpub")
        self.lineEdit_dpub.setGeometry(QRect(260, 170, 51, 20))
        self.lineEdit_ikp = QLineEdit(self.groupBox)
        self.lineEdit_ikp.setObjectName(u"lineEdit_ikp")
        self.lineEdit_ikp.setGeometry(QRect(120, 200, 51, 20))
        self.lineEdit_plb = QLineEdit(self.groupBox)
        self.lineEdit_plb.setObjectName(u"lineEdit_plb")
        self.lineEdit_plb.setGeometry(QRect(200, 200, 51, 20))
        self.lineEdit_pub = QLineEdit(self.groupBox)
        self.lineEdit_pub.setObjectName(u"lineEdit_pub")
        self.lineEdit_pub.setGeometry(QRect(260, 200, 51, 20))
        self.label_35 = QLabel(self.groupBox)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(20, 230, 81, 21))
        self.lineEdit_isite = QLineEdit(self.groupBox)
        self.lineEdit_isite.setObjectName(u"lineEdit_isite")
        self.lineEdit_isite.setGeometry(QRect(90, 230, 51, 20))
        self.label_36 = QLabel(self.groupBox)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(151, 230, 49, 21))
        self.lineEdit_siteub = QLineEdit(self.groupBox)
        self.lineEdit_siteub.setObjectName(u"lineEdit_siteub")
        self.lineEdit_siteub.setGeometry(QRect(260, 230, 51, 20))
        self.lineEdit_sitelb = QLineEdit(self.groupBox)
        self.lineEdit_sitelb.setObjectName(u"lineEdit_sitelb")
        self.lineEdit_sitelb.setGeometry(QRect(200, 230, 51, 20))
        self.pushButton_cls = QPushButton(self.groupBox)
        self.pushButton_cls.setObjectName(u"pushButton_cls")
        self.pushButton_cls.setGeometry(QRect(250, 290, 61, 23))
        self.label_37 = QLabel(self.groupBox)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(10, 260, 111, 21))
        self.lineEdit_icap = QLineEdit(self.groupBox)
        self.lineEdit_icap.setObjectName(u"lineEdit_icap")
        self.lineEdit_icap.setGeometry(QRect(120, 260, 31, 20))
        self.lineEdit_caplb = QLineEdit(self.groupBox)
        self.lineEdit_caplb.setObjectName(u"lineEdit_caplb")
        self.lineEdit_caplb.setGeometry(QRect(200, 260, 51, 20))
        self.label_38 = QLabel(self.groupBox)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(151, 260, 49, 21))
        self.lineEdit_capub = QLineEdit(self.groupBox)
        self.lineEdit_capub.setObjectName(u"lineEdit_capub")
        self.lineEdit_capub.setGeometry(QRect(260, 260, 51, 20))
        self.lineEdit_cycle = QLineEdit(self.page)
        self.lineEdit_cycle.setObjectName(u"lineEdit_cycle")
        self.lineEdit_cycle.setGeometry(QRect(290, 360, 61, 20))
        self.label_39 = QLabel(self.page)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(230, 360, 51, 21))
        self.pushButton_stp = QPushButton(self.page)
        self.pushButton_stp.setObjectName(u"pushButton_stp")
        self.pushButton_stp.setGeometry(QRect(370, 400, 81, 41))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.verticalLayoutWidget = QWidget(self.page_2)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 10, 791, 541))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.pushButton_db_2 = QPushButton(self.page_3)
        self.pushButton_db_2.setObjectName(u"pushButton_db_2")
        self.pushButton_db_2.setGeometry(QRect(10, 0, 161, 51))
        self.pushButton_rd_2 = QPushButton(self.page_3)
        self.pushButton_rd_2.setObjectName(u"pushButton_rd_2")
        self.pushButton_rd_2.setGeometry(QRect(10, 50, 161, 51))
        self.tableView_2 = QTableView(self.page_3)
        self.tableView_2.setObjectName(u"tableView_2")
        self.tableView_2.setGeometry(QRect(10, 150, 161, 371))
        self.checkBox = QCheckBox(self.page_3)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(20, 110, 101, 16))
        self.checkBox.hide()
        self.label_data_mode = QLabel(self.page_3)
        self.label_data_mode.setObjectName(u"label_data_mode")
        self.label_data_mode.setGeometry(QRect(10, 105, 51, 18))
        self.radioButton_mode_adsorption = QRadioButton(self.page_3)
        self.radioButton_mode_adsorption.setObjectName(u"radioButton_mode_adsorption")
        self.radioButton_mode_adsorption.setGeometry(QRect(60, 104, 105, 18))
        self.radioButton_mode_titration = QRadioButton(self.page_3)
        self.radioButton_mode_titration.setObjectName(u"radioButton_mode_titration")
        self.radioButton_mode_titration.setGeometry(QRect(60, 124, 105, 18))
        self.groupBox_5 = QGroupBox(self.page_3)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(180, 0, 241, 141))
        self.lineEdit_reactant = QLineEdit(self.groupBox_5)
        self.lineEdit_reactant.setObjectName(u"lineEdit_reactant")
        self.lineEdit_reactant.setGeometry(QRect(70, 110, 61, 20))
        self.label_cs_2 = QLabel(self.groupBox_5)
        self.label_cs_2.setObjectName(u"label_cs_2")
        self.label_cs_2.setGeometry(QRect(10, 50, 71, 21))
        self.label_ph_2 = QLabel(self.groupBox_5)
        self.label_ph_2.setObjectName(u"label_ph_2")
        self.label_ph_2.setGeometry(QRect(10, 80, 71, 21))
        self.label_vol_2 = QLabel(self.groupBox_5)
        self.label_vol_2.setObjectName(u"label_vol_2")
        self.label_vol_2.setGeometry(QRect(10, 110, 61, 21))
        self.lineEdit_cs_2 = QLineEdit(self.groupBox_5)
        self.lineEdit_cs_2.setObjectName(u"lineEdit_cs_2")
        self.lineEdit_cs_2.setGeometry(QRect(90, 80, 111, 20))
        self.lineEdit_cation = QLineEdit(self.groupBox_5)
        self.lineEdit_cation.setObjectName(u"lineEdit_cation")
        self.lineEdit_cation.setGeometry(QRect(50, 50, 51, 20))
        self.label_cs_3 = QLabel(self.groupBox_5)
        self.label_cs_3.setObjectName(u"label_cs_3")
        self.label_cs_3.setGeometry(QRect(110, 50, 71, 21))
        self.lineEdit_anion = QLineEdit(self.groupBox_5)
        self.lineEdit_anion.setObjectName(u"lineEdit_anion")
        self.lineEdit_anion.setGeometry(QRect(160, 50, 61, 20))
        self.lineEdit_moles = QLineEdit(self.groupBox_5)
        self.lineEdit_moles.setObjectName(u"lineEdit_moles")
        self.lineEdit_moles.setGeometry(QRect(140, 110, 61, 20))
        self.label_vol_3 = QLabel(self.groupBox_5)
        self.label_vol_3.setObjectName(u"label_vol_3")
        self.label_vol_3.setGeometry(QRect(200, 110, 61, 21))
        self.label_cs_4 = QLabel(self.groupBox_5)
        self.label_cs_4.setObjectName(u"label_cs_4")
        self.label_cs_4.setGeometry(QRect(10, 20, 51, 21))
        self.lineEdit_ph_4 = QLineEdit(self.groupBox_5)
        self.lineEdit_ph_4.setObjectName(u"lineEdit_ph_4")
        self.lineEdit_ph_4.setGeometry(QRect(60, 20, 71, 20))
        self.label_initial_vol = QLabel(self.groupBox_5)
        self.label_initial_vol.setObjectName(u"label_initial_vol")
        self.label_initial_vol.setGeometry(QRect(140, 20, 41, 21))
        self.lineEdit_ph_5 = QLineEdit(self.groupBox_5)
        self.lineEdit_ph_5.setObjectName(u"lineEdit_ph_5")
        self.lineEdit_ph_5.setGeometry(QRect(180, 20, 51, 20))
        self.groupBox_6 = QGroupBox(self.page_3)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(180, 150, 241, 161))
        self.label_13 = QLabel(self.groupBox_6)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(180, 60, 54, 12))
        self.radioButton_fx_2 = QRadioButton(self.groupBox_6)
        self.radioButton_fx_2.setObjectName(u"radioButton_fx_2")
        self.radioButton_fx_2.setGeometry(QRect(90, 20, 89, 16))
        self.radioButton_ds_2 = QRadioButton(self.groupBox_6)
        self.radioButton_ds_2.setObjectName(u"radioButton_ds_2")
        self.radioButton_ds_2.setGeometry(QRect(150, 20, 89, 16))
        self.lineEdit_base_2 = QLineEdit(self.groupBox_6)
        self.lineEdit_base_2.setObjectName(u"lineEdit_base_2")
        self.lineEdit_base_2.setGeometry(QRect(90, 60, 81, 20))
        self.comboBox_bs_2 = QComboBox(self.groupBox_6)
        self.comboBox_bs_2.addItem("")
        self.comboBox_bs_2.addItem("")
        self.comboBox_bs_2.setObjectName(u"comboBox_bs_2")
        self.comboBox_bs_2.setGeometry(QRect(10, 60, 69, 22))
        self.label_mix_2 = QLabel(self.groupBox_6)
        self.label_mix_2.setObjectName(u"label_mix_2")
        self.label_mix_2.setGeometry(QRect(10, 20, 81, 21))
        self.comboBox_ad_2 = QComboBox(self.groupBox_6)
        self.comboBox_ad_2.addItem("")
        self.comboBox_ad_2.addItem("")
        self.comboBox_ad_2.addItem("")
        self.comboBox_ad_2.setObjectName(u"comboBox_ad_2")
        self.comboBox_ad_2.setGeometry(QRect(10, 90, 69, 22))
        self.lineEdit_acid_2 = QLineEdit(self.groupBox_6)
        self.lineEdit_acid_2.setObjectName(u"lineEdit_acid_2")
        self.lineEdit_acid_2.setGeometry(QRect(90, 90, 81, 20))
        self.label_16 = QLabel(self.groupBox_6)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(180, 100, 54, 12))
        self.checkBox_7 = QCheckBox(self.groupBox_6)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(10, 40, 161, 16))
        self.label_mix_5 = QLabel(self.groupBox_6)
        self.label_mix_5.setObjectName(u"label_mix_5")
        self.label_mix_5.setGeometry(QRect(10, 120, 81, 21))
        self.textEdit = QTextEdit(self.groupBox_6)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(90, 120, 104, 31))
        self.groupBox_7 = QGroupBox(self.page_3)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(180, 320, 241, 51))
        self.comboBox = QComboBox(self.groupBox_7)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(10, 20, 69, 22))
        self.lineEdit_output = QLineEdit(self.groupBox_7)
        self.lineEdit_output.setObjectName(u"lineEdit_output")
        self.lineEdit_output.setGeometry(QRect(100, 20, 113, 20))
        self.lineEdit_cycle_2 = QLineEdit(self.page_3)
        self.lineEdit_cycle_2.setObjectName(u"lineEdit_cycle_2")
        self.lineEdit_cycle_2.setGeometry(QRect(250, 440, 61, 20))
        self.label_40 = QLabel(self.page_3)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(190, 440, 51, 21))
        self.pushButton_opt_2 = QPushButton(self.page_3)
        self.pushButton_opt_2.setObjectName(u"pushButton_opt_2")
        self.pushButton_opt_2.setGeometry(QRect(330, 370, 81, 61))
        self.label_41 = QLabel(self.page_3)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(190, 410, 71, 21))
        self.pushButton_stp_2 = QPushButton(self.page_3)
        self.pushButton_stp_2.setObjectName(u"pushButton_stp_2")
        self.pushButton_stp_2.setGeometry(QRect(330, 430, 81, 41))
        self.label_42 = QLabel(self.page_3)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(190, 380, 71, 21))
        self.lineEdit_iter_2 = QLineEdit(self.page_3)
        self.lineEdit_iter_2.setObjectName(u"lineEdit_iter_2")
        self.lineEdit_iter_2.setGeometry(QRect(250, 380, 61, 20))
        self.lineEdit_temp_2 = QLineEdit(self.page_3)
        self.lineEdit_temp_2.setObjectName(u"lineEdit_temp_2")
        self.lineEdit_temp_2.setGeometry(QRect(250, 410, 61, 20))
        self.groupBox_8 = QGroupBox(self.page_3)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(180, 470, 611, 81))
        self.textEdit_res_2 = QTextEdit(self.groupBox_8)
        self.textEdit_res_2.setObjectName(u"textEdit_res_2")
        self.textEdit_res_2.setGeometry(QRect(0, 20, 611, 61))
        self.groupBox_9 = QGroupBox(self.page_3)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(430, 0, 361, 471))
        self.textEdit_sf_2 = QTextEdit(self.groupBox_9)
        self.textEdit_sf_2.setObjectName(u"textEdit_sf_2")
        self.textEdit_sf_2.setGeometry(QRect(10, 390, 341, 81))
        self.pushButton_addsf_2 = QPushButton(self.groupBox_9)
        self.pushButton_addsf_2.setObjectName(u"pushButton_addsf_2")
        self.pushButton_addsf_2.setGeometry(QRect(230, 80, 91, 23))
        self.comboBox_mdl_2 = QComboBox(self.groupBox_9)
        self.comboBox_mdl_2.addItem("")
        self.comboBox_mdl_2.addItem("")
        self.comboBox_mdl_2.addItem("")
        self.comboBox_mdl_2.addItem("")
        self.comboBox_mdl_2.setObjectName(u"comboBox_mdl_2")
        self.comboBox_mdl_2.setGeometry(QRect(130, 110, 69, 22))
        self.lineEdit_sarea_2 = QLineEdit(self.groupBox_9)
        self.lineEdit_sarea_2.setObjectName(u"lineEdit_sarea_2")
        self.lineEdit_sarea_2.setGeometry(QRect(110, 50, 61, 20))
        self.lineEdit_sname_2 = QLineEdit(self.groupBox_9)
        self.lineEdit_sname_2.setObjectName(u"lineEdit_sname_2")
        self.lineEdit_sname_2.setGeometry(QRect(110, 20, 61, 20))
        self.label_43 = QLabel(self.groupBox_9)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(20, 20, 81, 21))
        self.lineEdit_smass_2 = QLineEdit(self.groupBox_9)
        self.lineEdit_smass_2.setObjectName(u"lineEdit_smass_2")
        self.lineEdit_smass_2.setGeometry(QRect(110, 80, 61, 20))
        self.label_44 = QLabel(self.groupBox_9)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(20, 50, 81, 21))
        self.label_45 = QLabel(self.groupBox_9)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(180, 50, 41, 21))
        self.label_46 = QLabel(self.groupBox_9)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(20, 80, 81, 21))
        self.label_47 = QLabel(self.groupBox_9)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(180, 80, 21, 21))
        self.label_48 = QLabel(self.groupBox_9)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(20, 110, 101, 21))
        self.pushButton_addreact = QPushButton(self.groupBox_9)
        self.pushButton_addreact.setObjectName(u"pushButton_addreact")
        self.pushButton_addreact.setGeometry(QRect(10, 360, 101, 23))
        self.label_49 = QLabel(self.groupBox_9)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(100, 160, 81, 21))
        self.label_50 = QLabel(self.groupBox_9)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(230, 160, 81, 21))
        self.label_51 = QLabel(self.groupBox_9)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(20, 140, 61, 21))
        self.lineEdit_reaction = QLineEdit(self.groupBox_9)
        self.lineEdit_reaction.setObjectName(u"lineEdit_reaction")
        self.lineEdit_reaction.setGeometry(QRect(70, 140, 281, 20))
        self.lineEdit_siteub_2 = QLineEdit(self.groupBox_9)
        self.lineEdit_siteub_2.setObjectName(u"lineEdit_siteub_2")
        self.lineEdit_siteub_2.setGeometry(QRect(260, 180, 51, 20))
        self.lineEdit_isite_2 = QLineEdit(self.groupBox_9)
        self.lineEdit_isite_2.setObjectName(u"lineEdit_isite_2")
        self.lineEdit_isite_2.setGeometry(QRect(110, 180, 51, 20))
        self.lineEdit_sitelb_2 = QLineEdit(self.groupBox_9)
        self.lineEdit_sitelb_2.setObjectName(u"lineEdit_sitelb_2")
        self.lineEdit_sitelb_2.setGeometry(QRect(190, 180, 51, 20))
        self.checkBox_site = QCheckBox(self.groupBox_9)
        self.checkBox_site.setObjectName(u"checkBox_site")
        self.checkBox_site.setGeometry(QRect(10, 180, 91, 21))
        self.checkBox_c1 = QCheckBox(self.groupBox_9)
        self.checkBox_c1.setObjectName(u"checkBox_c1")
        self.checkBox_c1.setGeometry(QRect(10, 210, 91, 21))
        self.checkBox_c2 = QCheckBox(self.groupBox_9)
        self.checkBox_c2.setObjectName(u"checkBox_c2")
        self.checkBox_c2.setGeometry(QRect(10, 240, 91, 21))
        self.checkBox_logk = QCheckBox(self.groupBox_9)
        self.checkBox_logk.setObjectName(u"checkBox_logk")
        self.checkBox_logk.setGeometry(QRect(10, 270, 91, 21))
        self.lineEdit_ic1 = QLineEdit(self.groupBox_9)
        self.lineEdit_ic1.setObjectName(u"lineEdit_ic1")
        self.lineEdit_ic1.setGeometry(QRect(110, 210, 51, 20))
        self.lineEdit_ic2 = QLineEdit(self.groupBox_9)
        self.lineEdit_ic2.setObjectName(u"lineEdit_ic2")
        self.lineEdit_ic2.setGeometry(QRect(110, 240, 51, 20))
        self.lineEdit_ik = QLineEdit(self.groupBox_9)
        self.lineEdit_ik.setObjectName(u"lineEdit_ik")
        self.lineEdit_ik.setGeometry(QRect(110, 270, 51, 20))
        self.lineEdit_ic1ub = QLineEdit(self.groupBox_9)
        self.lineEdit_ic1ub.setObjectName(u"lineEdit_ic1ub")
        self.lineEdit_ic1ub.setGeometry(QRect(260, 210, 51, 20))
        self.lineEdit_ic1lb = QLineEdit(self.groupBox_9)
        self.lineEdit_ic1lb.setObjectName(u"lineEdit_ic1lb")
        self.lineEdit_ic1lb.setGeometry(QRect(190, 210, 51, 20))
        self.lineEdit_ic2lb = QLineEdit(self.groupBox_9)
        self.lineEdit_ic2lb.setObjectName(u"lineEdit_ic2lb")
        self.lineEdit_ic2lb.setGeometry(QRect(190, 240, 51, 20))
        self.lineEdit_ic2ub = QLineEdit(self.groupBox_9)
        self.lineEdit_ic2ub.setObjectName(u"lineEdit_ic2ub")
        self.lineEdit_ic2ub.setGeometry(QRect(260, 240, 51, 20))
        self.lineEdit_iklb = QLineEdit(self.groupBox_9)
        self.lineEdit_iklb.setObjectName(u"lineEdit_iklb")
        self.lineEdit_iklb.setGeometry(QRect(190, 270, 51, 20))
        self.lineEdit_ikub = QLineEdit(self.groupBox_9)
        self.lineEdit_ikub.setObjectName(u"lineEdit_ikub")
        self.lineEdit_ikub.setGeometry(QRect(260, 270, 51, 20))
        self.comboBox_charge = QComboBox(self.groupBox_9)
        self.comboBox_charge.addItem("")
        self.comboBox_charge.addItem("")
        self.comboBox_charge.setObjectName(u"comboBox_charge")
        self.comboBox_charge.setGeometry(QRect(110, 330, 69, 22))
        self.checkBox_z1 = QCheckBox(self.groupBox_9)
        self.checkBox_z1.setObjectName(u"checkBox_z1")
        self.checkBox_z1.setGeometry(QRect(10, 300, 61, 21))
        self.label_52 = QLabel(self.groupBox_9)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(10, 160, 51, 21))
        self.lineEdit_iz1 = QLineEdit(self.groupBox_9)
        self.lineEdit_iz1.setObjectName(u"lineEdit_iz1")
        self.lineEdit_iz1.setGeometry(QRect(110, 300, 51, 20))
        self.lineEdit_iz1lb = QLineEdit(self.groupBox_9)
        self.lineEdit_iz1lb.setObjectName(u"lineEdit_iz1lb")
        self.lineEdit_iz1lb.setGeometry(QRect(190, 300, 51, 20))
        self.lineEdit_iz1ub = QLineEdit(self.groupBox_9)
        self.lineEdit_iz1ub.setObjectName(u"lineEdit_iz1ub")
        self.lineEdit_iz1ub.setGeometry(QRect(260, 300, 51, 20))
        self.lineEdit_totalz = QLineEdit(self.groupBox_9)
        self.lineEdit_totalz.setObjectName(u"lineEdit_totalz")
        self.lineEdit_totalz.setGeometry(QRect(190, 330, 51, 20))
        self.pushButton_delreact = QPushButton(self.groupBox_9)
        self.pushButton_delreact.setObjectName(u"pushButton_delreact")
        self.pushButton_delreact.setGeometry(QRect(120, 360, 91, 23))
        self.pushButton_delsf = QPushButton(self.groupBox_9)
        self.pushButton_delsf.setObjectName(u"pushButton_delsf")
        self.pushButton_delsf.setGeometry(QRect(230, 110, 91, 23))
        self.pushButton_cls_4 = QPushButton(self.groupBox_9)
        self.pushButton_cls_4.setObjectName(u"pushButton_cls_4")
        self.pushButton_cls_4.setGeometry(QRect(220, 360, 91, 23))
        self.lineEdit_sformula = QLineEdit(self.groupBox_9)
        self.lineEdit_sformula.setObjectName(u"lineEdit_sformula")
        self.lineEdit_sformula.setGeometry(QRect(240, 20, 113, 20))
        self.label_53 = QLabel(self.groupBox_9)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(180, 20, 81, 21))
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 810, 23))
        self.menuTitration = QMenu(self.menubar)
        self.menuTitration.setObjectName(u"menuTitration")
        self.menuAlgorithm = QMenu(self.menubar)
        self.menuAlgorithm.setObjectName(u"menuAlgorithm")
        self.menuDirectory = QMenu(self.menubar)
        self.menuDirectory.setObjectName(u"menuDirectory")
        self.menuInit_protonation = QMenu(self.menubar)
        self.menuInit_protonation.setObjectName(u"menuInit_protonation")
        self.menuHistory = QMenu(self.menubar)
        self.menuHistory.setObjectName(u"menuHistory")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuTitration.menuAction())
        self.menubar.addAction(self.menuAlgorithm.menuAction())
        self.menubar.addAction(self.menuDirectory.menuAction())
        self.menubar.addAction(self.menuInit_protonation.menuAction())
        self.menubar.addAction(self.menuHistory.menuAction())
        self.menuTitration.addAction(self.actionTitration)
        self.menuTitration.addAction(self.actionPlot)
        self.menuTitration.addAction(self.actionAdvanced)
        self.menuAlgorithm.addAction(self.actiondifferential_evolution)
        self.menuAlgorithm.addAction(self.actionDual_annealing)
        self.menuAlgorithm.addAction(self.actionnelder_mead)
        self.menuDirectory.addAction(self.actionDatabase_folder)
        self.menuDirectory.addAction(self.actionData_folder)
        self.menuDirectory.addAction(self.actionOutput_folder)
        self.menuInit_protonation.addAction(self.actionDisabled)
        self.menuInit_protonation.addAction(self.actionEnabled)
        self.menuHistory.addAction(self.actionSave_settings)
        self.menuHistory.addAction(self.actionLoad_settings)
        self.menuHistory.addSeparator()
        self.menuHistory.addAction(self.actionCompare_results)
        self.menuHistory.addAction(self.actionOpen_output_folder)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)

        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"PhreeFit", None))
        self.actionDatabase_path.setText(QCoreApplication.translate("MainWindow", u"Database path", None))
        self.actionparameters.setText(QCoreApplication.translate("MainWindow", u"Parameters", None))
        self.actionpp.setText(QCoreApplication.translate("MainWindow", u"pp", None))
        self.actionTitration.setText(QCoreApplication.translate("MainWindow", u"Titration", None))
        self.actionPlot.setText(QCoreApplication.translate("MainWindow", u"Plot", None))
        self.actionAdvanced.setText(QCoreApplication.translate("MainWindow", u"Advanced", None))
        self.actiondifferential_evolution.setText(
            QCoreApplication.translate("MainWindow", u"Differential evolution", None))
        self.actionDual_annealing.setText(QCoreApplication.translate("MainWindow", u"Dual annealing", None))
        self.actionnelder_mead.setText(QCoreApplication.translate("MainWindow", u"Nelder Mead", None))
        self.actionDatabase_folder.setText(QCoreApplication.translate("MainWindow", u"Database path", None))
        self.actionOutput_folder.setText(QCoreApplication.translate("MainWindow", u"Output path", None))
        self.actionDisabled.setText(QCoreApplication.translate("MainWindow", u"Disabled", None))
        # self.actionpH_2.setText(QCoreApplication.translate("MainWindow", u"pH", None))
        # self.actionIS_2.setText(QCoreApplication.translate("MainWindow", u"IS", None))
        self.actionEnabled.setText(QCoreApplication.translate("MainWindow", u"Enabled", None))
        self.actionData_folder.setText(QCoreApplication.translate("MainWindow", u"Data path", None))
        self.actionSave_settings.setText(QCoreApplication.translate("MainWindow", u"Save settings", None))
        self.actionLoad_settings.setText(QCoreApplication.translate("MainWindow", u"Load settings", None))
        self.actionCompare_results.setText(QCoreApplication.translate("MainWindow", u"Compare results", None))
        self.actionOpen_output_folder.setText(QCoreApplication.translate("MainWindow", u"Open output folder", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"T", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Max iter:", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Titration solution", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"mol/L", None))
        self.radioButton_fx.setText(QCoreApplication.translate("MainWindow", u"Fix pH", None))
        self.radioButton_ds.setText(QCoreApplication.translate("MainWindow", u"Dissolution", None))
        self.comboBox_bs.setItemText(0, QCoreApplication.translate("MainWindow", u"NaOH", None))
        self.comboBox_bs.setItemText(1, QCoreApplication.translate("MainWindow", u"KOH", None))

        self.label_mix.setText(QCoreApplication.translate("MainWindow", u"Solution type", None))
        self.comboBox_ad.setItemText(0, QCoreApplication.translate("MainWindow", u"HCl", None))
        self.comboBox_ad.setItemText(1, QCoreApplication.translate("MainWindow", u"HNO3", None))

        self.label_15.setText(QCoreApplication.translate("MainWindow", u"mol/L", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Initial Solution", None))
        self.label_cs.setText(QCoreApplication.translate("MainWindow", u"IS mol/L", None))
        self.label_ph.setText(QCoreApplication.translate("MainWindow", u"Initial pH", None))
        self.label_vol.setText(QCoreApplication.translate("MainWindow", u"Initial volume mL", None))
        self.pushButton_db.setText(QCoreApplication.translate("MainWindow", u"Database", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Results", None))
        self.pushButton_rd.setText(QCoreApplication.translate("MainWindow", u"Read Titration data", None))
        self.pushButton_opt.setText(QCoreApplication.translate("MainWindow", u"Optimize", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Set Surface parameters", None))
        self.pushButton_addsf.setText(QCoreApplication.translate("MainWindow", u"Add surface", None))
        self.comboBox_mdl.setItemText(0, QCoreApplication.translate("MainWindow", u"NEM", None))
        self.comboBox_mdl.setItemText(1, QCoreApplication.translate("MainWindow", u"CCM", None))
        self.comboBox_mdl.setItemText(2, QCoreApplication.translate("MainWindow", u"GDDL", None))

        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Surface name", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Surface area", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"m2/g", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Surface mass", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"g", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Surface model", None))
        self.pushButton_review.setText(QCoreApplication.translate("MainWindow", u"Review reactions", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Initial Logk", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"LogK bounds", None))
        self.checkBox_dpro.setText(QCoreApplication.translate("MainWindow", u"Acidic site", None))
        self.checkBox_pro.setText(QCoreApplication.translate("MainWindow", u"Basic site", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Site (mole)", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Bounds", None))
        self.pushButton_cls.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Capacitance (F/m2)", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Bounds", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Cores", None))
        self.pushButton_stp.setText(QCoreApplication.translate("MainWindow", u"Terminate", None))
        self.pushButton_db_2.setText(QCoreApplication.translate("MainWindow", u"Database", None))
        self.pushButton_rd_2.setText(QCoreApplication.translate("MainWindow", u"Read exp data", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Titration", None))
        self.label_data_mode.setText(QCoreApplication.translate("MainWindow", u"Mode:", None))
        self.radioButton_mode_adsorption.setText(QCoreApplication.translate("MainWindow", u"Adsorption", None))
        self.radioButton_mode_titration.setText(QCoreApplication.translate("MainWindow", u"Titration", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Initial Solution", None))
        self.label_cs_2.setText(QCoreApplication.translate("MainWindow", u"Cation", None))
        self.label_ph_2.setText(QCoreApplication.translate("MainWindow", u"Conc (mol/L)", None))
        self.label_vol_2.setText(QCoreApplication.translate("MainWindow", u"Reactant", None))
        self.label_cs_3.setText(QCoreApplication.translate("MainWindow", u"Anion", None))
        self.label_vol_3.setText(QCoreApplication.translate("MainWindow", u"mol/L", None))
        self.label_cs_4.setText(QCoreApplication.translate("MainWindow", u"Initial pH", None))
        self.label_initial_vol.setText(QCoreApplication.translate("MainWindow", u"V (mL)", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Equilibrium or Titration solution", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"mol/L", None))
        self.radioButton_fx_2.setText(QCoreApplication.translate("MainWindow", u"Fix pH", None))
        self.radioButton_ds_2.setText(QCoreApplication.translate("MainWindow", u"Dissolve", None))
        self.comboBox_bs_2.setItemText(0, QCoreApplication.translate("MainWindow", u"NaOH", None))
        self.comboBox_bs_2.setItemText(1, QCoreApplication.translate("MainWindow", u"KOH", None))

        self.label_mix_2.setText(QCoreApplication.translate("MainWindow", u"Type", None))
        self.comboBox_ad_2.setItemText(0, QCoreApplication.translate("MainWindow", u"HCl", None))
        self.comboBox_ad_2.setItemText(1, QCoreApplication.translate("MainWindow", u"H2SO4", None))
        self.comboBox_ad_2.setItemText(2, QCoreApplication.translate("MainWindow", u"HNO3", None))

        self.label_16.setText(QCoreApplication.translate("MainWindow", u"mol/L", None))
        self.checkBox_7.setText(QCoreApplication.translate("MainWindow", u"Automatic pH", None))
        self.label_mix_5.setText(QCoreApplication.translate("MainWindow", u"Eq Phase:", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Output", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"totals", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"activities", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"molalities ", None))

        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Cores", None))
        self.pushButton_opt_2.setText(QCoreApplication.translate("MainWindow", u"Optimize", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"T", None))
        self.pushButton_stp_2.setText(QCoreApplication.translate("MainWindow", u"Terminate", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Max iter:", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Results", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Set Surface parameters", None))
        self.pushButton_addsf_2.setText(QCoreApplication.translate("MainWindow", u"Add surface", None))
        self.comboBox_mdl_2.setItemText(0, QCoreApplication.translate("MainWindow", u"NEM", None))
        self.comboBox_mdl_2.setItemText(1, QCoreApplication.translate("MainWindow", u"CCM", None))
        self.comboBox_mdl_2.setItemText(2, QCoreApplication.translate("MainWindow", u"GDDL", None))
        self.comboBox_mdl_2.setItemText(3, QCoreApplication.translate("MainWindow", u"CDMUSIC", None))

        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Surface name", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Surface area", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"m2/g", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"Surface mass", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"g", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"Model selection", None))
        self.pushButton_addreact.setText(QCoreApplication.translate("MainWindow", u"Add reaction", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"Initial value", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"Bounds", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"Reaction", None))
        self.lineEdit_reaction.setText("")
        self.checkBox_site.setText(QCoreApplication.translate("MainWindow", u"Site (moles)", None))
        self.checkBox_c1.setText(QCoreApplication.translate("MainWindow", u"C1 (F/m2)", None))
        self.checkBox_c2.setText(QCoreApplication.translate("MainWindow", u"C2 (F/m2)", None))
        self.checkBox_logk.setText(QCoreApplication.translate("MainWindow", u"   log_k", None))
        self.comboBox_charge.setItemText(0, QCoreApplication.translate("MainWindow", u"z0+z1", None))
        self.comboBox_charge.setItemText(1, QCoreApplication.translate("MainWindow", u"z1+zd", None))

        self.checkBox_z1.setText(QCoreApplication.translate("MainWindow", u"   z1", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"Fix", None))
        self.pushButton_delreact.setText(QCoreApplication.translate("MainWindow", u"Del reaction", None))
        self.pushButton_delsf.setText(QCoreApplication.translate("MainWindow", u"Del surface", None))
        self.pushButton_cls_4.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"Formula", None))
        self.menuTitration.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuAlgorithm.setTitle(QCoreApplication.translate("MainWindow", u"Algorithm", None))
        self.menuDirectory.setTitle(QCoreApplication.translate("MainWindow", u"Directory", None))
        self.menuInit_protonation.setTitle(QCoreApplication.translate("MainWindow", u"Pre-equilibrate", None))
        self.menuHistory.setTitle(QCoreApplication.translate("MainWindow", u"History", None))
        # retranslateUi
        self.lineEdit_ikp.setText("0")
        self.lineEdit_ikdp.setText("0")
        self.lineEdit_dplb.setText("-10")
        self.lineEdit_dpub.setText("10")
        self.lineEdit_plb.setText("-10")
        self.lineEdit_pub.setText("10")
        self.lineEdit_isite.setText("0.0001")
        self.lineEdit_siteub.setText("0.01")
        self.lineEdit_sitelb.setText("0")
        self.lineEdit_iter.setText("1000")
        self.lineEdit_temp.setText("6000")
        self.radioButton_ds.setChecked(True)
        self.radioButton_ds_2.setChecked(True)
        self.lineEdit_icap.setText("1")
        self.lineEdit_caplb.setText("0")
        self.lineEdit_capub.setText("5")
        self.lineEdit_cycle.setText("1")
        self.pushButton_stp.setEnabled(False)
        self.lineEdit_base.setText("0")
        self.lineEdit_acid.setText("0")
        self.lineEdit_temp.setValidator(QIntValidator())
        self.lineEdit_iter.setValidator(QIntValidator())
        self.lineEdit_sarea.setValidator(QDoubleValidator())
        self.lineEdit_smass.setValidator(QDoubleValidator())
        self.lineEdit_cs.setValidator(QDoubleValidator())
        self.lineEdit_vol.setValidator(QDoubleValidator())
        self.lineEdit_ph.setValidator(QDoubleValidator())
        self.textEdit_sf.setReadOnly(True)
        self.textEdit_res.setReadOnly(True)
        self.lineEdit_ik.setText("0")
        self.lineEdit_iklb.setText("-10")
        self.lineEdit_ikub.setText("10")
        self.lineEdit_isite_2.setText("0.0001")
        self.lineEdit_sitelb_2.setText("0")
        self.lineEdit_siteub_2.setText("0.01")
        self.lineEdit_ic1.setText("1")
        self.lineEdit_ic1lb.setText("0")
        self.lineEdit_ic1ub.setText("5")
        self.lineEdit_ic2.setText("1")
        self.lineEdit_ic2lb.setText("0")
        self.lineEdit_ic2ub.setText("1")
        self.lineEdit_iter_2.setText("1000")
        self.lineEdit_temp_2.setText("6000")
        self.radioButton_ds.setChecked(True)
        self.lineEdit_iz1.setText("1")
        self.lineEdit_iz1lb.setText("-1")
        self.lineEdit_iz1ub.setText("1")
        self.lineEdit_totalz.setText("1")
        self.lineEdit_cycle_2.setText("1")
        self.pushButton_stp_2.setEnabled(False)
        self.radioButton_mode_adsorption.setChecked(True)
        self.lineEdit_base_2.setText("0")
        self.lineEdit_acid_2.setText("0")
        self.lineEdit_ph_5.setText("1000")
        self.checkBox_logk.setChecked(True)
        self.checkBox_site.setChecked(True)
        self.checkBox_c1.setChecked(True)
        self.checkBox_c2.setChecked(True)
        self.checkBox_z1.setChecked(True)
        self.lineEdit_temp_2.setValidator(QIntValidator())
        self.lineEdit_cycle.setValidator(QIntValidator())
        self.lineEdit_cycle_2.setValidator(QIntValidator())
        self.lineEdit_iter_2.setValidator(QIntValidator())
        self.lineEdit_sarea_2.setValidator(QDoubleValidator())
        self.lineEdit_smass_2.setValidator(QDoubleValidator())
        self.lineEdit_cs_2.setValidator(QDoubleValidator())
        self.lineEdit_ph_4.setValidator(QDoubleValidator())
        self.lineEdit_ph_5.setValidator(QDoubleValidator())


BASE_PAGE_WIDTH = 801
BASE_PAGE_HEIGHT = 551
MINIMUM_SCALE = 0.78
MAXIMUM_SCALE = 2.0


@dataclass
class _WidgetGeometry:
    widget: QWidget
    geometry: QRect
    top_level: bool
    point_size: float
    pixel_size: int


class ResponsiveLayoutManager(QObject):
    """Scale the two form pages while allowing the plot page to fill space."""

    def __init__(self, window):
        super().__init__(window)
        self.window = window
        self.pages = (window.page, window.page_3)
        self._records = {page: self._capture_page(page) for page in self.pages}
        self._table_row_heights = {
            table: table.verticalHeader().defaultSectionSize()
            for table in (window.tableView, window.tableView_2)
        }
        self._update_pending = False

        self._install_container_layouts()
        self._configure_tables()
        window.setMinimumSize(720, 540)

        window.stackedWidget.installEventFilter(self)
        for page in self.pages:
            page.installEventFilter(self)
        self.schedule_update()

    def _install_container_layouts(self):
        central_layout = self.window.centralwidget.layout()
        if central_layout is None:
            central_layout = QVBoxLayout(self.window.centralwidget)
            central_layout.setContentsMargins(0, 0, 0, 0)
            central_layout.setSpacing(0)
            central_layout.addWidget(self.window.stackedWidget)

        plot_layout = self.window.page_2.layout()
        if plot_layout is None:
            plot_layout = QVBoxLayout(self.window.page_2)
            plot_layout.setContentsMargins(8, 8, 8, 8)
            plot_layout.setSpacing(0)
            plot_layout.addWidget(self.window.verticalLayoutWidget)

    def _configure_tables(self):
        for table in (self.window.tableView, self.window.tableView_2):
            table.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
            table.horizontalHeader().setStretchLastSection(True)

    def _capture_page(self, page):
        records = []

        def capture_children(parent, top_level):
            children = parent.findChildren(
                QWidget,
                options=Qt.FindChildOption.FindDirectChildrenOnly,
            )
            for child in children:
                font = child.font()
                records.append(_WidgetGeometry(
                    widget=child,
                    geometry=QRect(child.geometry()),
                    top_level=top_level,
                    point_size=font.pointSizeF(),
                    pixel_size=font.pixelSize(),
                ))
                if isinstance(child, QGroupBox):
                    capture_children(child, False)

        capture_children(page, True)
        return records

    def eventFilter(self, watched, event):
        if event.type() in (QEvent.Type.Resize, QEvent.Type.Show):
            self.schedule_update()
        return super().eventFilter(watched, event)

    def schedule_update(self):
        if self._update_pending:
            return
        self._update_pending = True
        QTimer.singleShot(0, self._update_geometry)

    def _update_geometry(self):
        self._update_pending = False
        for page in self.pages:
            width = max(1, page.width())
            height = max(1, page.height())
            scale = min(width / BASE_PAGE_WIDTH, height / BASE_PAGE_HEIGHT)
            scale = max(MINIMUM_SCALE, min(MAXIMUM_SCALE, scale))
            content_width = BASE_PAGE_WIDTH * scale
            content_height = BASE_PAGE_HEIGHT * scale
            offset_x = max(0.0, (width - content_width) / 2.0)
            offset_y = max(0.0, (height - content_height) / 2.0)

            for record in self._records[page]:
                base = record.geometry
                x_offset = offset_x if record.top_level else 0.0
                y_offset = offset_y if record.top_level else 0.0
                record.widget.setGeometry(
                    round(base.x() * scale + x_offset),
                    round(base.y() * scale + y_offset),
                    max(1, round(base.width() * scale)),
                    max(1, round(base.height() * scale)),
                )
                font = record.widget.font()
                if record.pixel_size > 0:
                    font.setPixelSize(max(8, round(record.pixel_size * scale)))
                elif record.point_size > 0:
                    font.setPointSizeF(max(7.5, record.point_size * scale))
                record.widget.setFont(font)

        for table, base_height in self._table_row_heights.items():
            page = table.parentWidget()
            while page not in self.pages and page is not None:
                page = page.parentWidget()
            if page is None:
                continue
            scale = min(page.width() / BASE_PAGE_WIDTH, page.height() / BASE_PAGE_HEIGHT)
            scale = max(MINIMUM_SCALE, min(MAXIMUM_SCALE, scale))
            table.verticalHeader().setDefaultSectionSize(max(18, round(base_height * scale)))
