# -*- coding: utf-8 -*-

"""Qt widget construction and responsive sizing for the PhreeFit main window.

This module intentionally contains no signal wiring, file I/O, or calculation logic.
"""

from PySide6.QtCore import QCoreApplication, QMetaObject, QObject, Qt
from PySide6.QtGui import QAction, QDoubleValidator, QFont, QIntValidator
from PySide6.QtWidgets import (
    QCheckBox, QComboBox, QFormLayout, QGridLayout, QGroupBox, QHeaderView,
    QHBoxLayout, QLabel, QLineEdit, QMenu, QMenuBar, QPushButton, QRadioButton,
    QScrollArea, QSizePolicy, QSplitter, QStackedWidget, QStatusBar, QTableView,
    QTextEdit, QVBoxLayout, QWidget,
)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1100, 720)
        self.actionDatabase_path = QAction(MainWindow)
        self.actionDatabase_path.setObjectName(u"actionDatabase_path")
        self.actionparameters = QAction(MainWindow)
        self.actionparameters.setObjectName(u"actionparameters")
        self.actionpp = QAction(MainWindow)
        self.actionpp.setObjectName(u"actionpp")
        self.actionTitration = QAction(MainWindow)
        self.actionTitration.setObjectName(u"actionTitration")
        font = QFont(MainWindow.font())
        self.actionTitration.setFont(font)
        self.actionPlot = QAction(MainWindow)
        self.actionPlot.setObjectName(u"actionPlot")
        self.actionPlot.setFont(font)
        self.actionAdvanced = QAction(MainWindow)
        self.actionAdvanced.setObjectName(u"actionAdvanced")
        self.actionAdvanced.setFont(font)
        self.actiondifferential_evolution = QAction(MainWindow)
        self.actiondifferential_evolution.setObjectName(u"actiondifferential_evolution")
        self.actiondifferential_evolution.setCheckable(True)
        self.actiondifferential_evolution.setChecked(True)
        self.actiondifferential_evolution.setFont(font)
        self.actionDual_annealing = QAction(MainWindow)
        self.actionDual_annealing.setObjectName(u"actionDual_annealing")
        self.actionDual_annealing.setCheckable(True)
        self.actionDual_annealing.setFont(font)
        self.actionnelder_mead = QAction(MainWindow)
        self.actionnelder_mead.setObjectName(u"actionnelder_mead")
        self.actionnelder_mead.setCheckable(True)
        self.actionnelder_mead.setFont(font)
        self.actionDatabase_folder = QAction(MainWindow)
        self.actionDatabase_folder.setObjectName(u"actionDatabase_folder")
        self.actionDatabase_folder.setFont(font)
        self.actionOutput_folder = QAction(MainWindow)
        self.actionOutput_folder.setObjectName(u"actionOutput_folder")
        self.actionOutput_folder.setFont(font)
        self.actionDisabled = QAction(MainWindow)
        self.actionDisabled.setObjectName(u"actionDisabled")
        self.actionDisabled.setCheckable(True)
        self.actionDisabled.setChecked(True)
        self.actionDisabled.setFont(font)
        self.actionEnabled = QAction(MainWindow)
        self.actionEnabled.setObjectName(u"actionEnabled")
        self.actionEnabled.setCheckable(True)
        self.actionEnabled.setChecked(False)
        self.actionEnabled.setFont(font)
        self.actionData_folder = QAction(MainWindow)
        self.actionData_folder.setObjectName(u"actionData_folder")
        self.actionSave_settings = QAction(MainWindow)
        self.actionSave_settings.setObjectName(u"actionSave_settings")
        self.actionLoad_settings = QAction(MainWindow)
        self.actionLoad_settings.setObjectName(u"actionLoad_settings")
        self.actionCompare_results = QAction(MainWindow)
        self.actionCompare_results.setObjectName(u"actionCompare_results")
        self.actionOpen_output_folder = QAction(MainWindow)
        self.actionOpen_output_folder.setObjectName(u"actionOpen_output_folder")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setFont(font)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.label_28 = QLabel(self.page)
        self.label_28.setObjectName(u"label_28")
        self.label_27 = QLabel(self.page)
        self.label_27.setObjectName(u"label_27")
        self.groupBox_2 = QGroupBox(self.page)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")
        self.radioButton_fx = QRadioButton(self.groupBox_2)
        self.radioButton_fx.setObjectName(u"radioButton_fx")
        self.radioButton_ds = QRadioButton(self.groupBox_2)
        self.radioButton_ds.setObjectName(u"radioButton_ds")
        self.lineEdit_base = QLineEdit(self.groupBox_2)
        self.lineEdit_base.setObjectName(u"lineEdit_base")
        self.comboBox_bs = QComboBox(self.groupBox_2)
        self.comboBox_bs.addItem("")
        self.comboBox_bs.addItem("")
        self.comboBox_bs.setObjectName(u"comboBox_bs")
        self.label_mix = QLabel(self.groupBox_2)
        self.label_mix.setObjectName(u"label_mix")
        self.comboBox_ad = QComboBox(self.groupBox_2)
        self.comboBox_ad.addItem("")
        self.comboBox_ad.addItem("")
        self.comboBox_ad.setObjectName(u"comboBox_ad")
        self.lineEdit_acid = QLineEdit(self.groupBox_2)
        self.lineEdit_acid.setObjectName(u"lineEdit_acid")
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.groupBox_3 = QGroupBox(self.page)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.lineEdit_vol = QLineEdit(self.groupBox_3)
        self.lineEdit_vol.setObjectName(u"lineEdit_vol")
        self.label_cs = QLabel(self.groupBox_3)
        self.label_cs.setObjectName(u"label_cs")
        self.label_ph = QLabel(self.groupBox_3)
        self.label_ph.setObjectName(u"label_ph")
        self.label_vol = QLabel(self.groupBox_3)
        self.label_vol.setObjectName(u"label_vol")
        self.lineEdit_ph = QLineEdit(self.groupBox_3)
        self.lineEdit_ph.setObjectName(u"lineEdit_ph")
        self.lineEdit_cs = QLineEdit(self.groupBox_3)
        self.lineEdit_cs.setObjectName(u"lineEdit_cs")
        self.lineEdit_iter = QLineEdit(self.page)
        self.lineEdit_iter.setObjectName(u"lineEdit_iter")
        self.pushButton_db = QPushButton(self.page)
        self.pushButton_db.setObjectName(u"pushButton_db")
        self.groupBox_4 = QGroupBox(self.page)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.textEdit_res = QTextEdit(self.groupBox_4)
        self.textEdit_res.setObjectName(u"textEdit_res")
        self.pushButton_rd = QPushButton(self.page)
        self.pushButton_rd.setObjectName(u"pushButton_rd")
        self.lineEdit_temp = QLineEdit(self.page)
        self.lineEdit_temp.setObjectName(u"lineEdit_temp")
        self.pushButton_opt = QPushButton(self.page)
        self.pushButton_opt.setObjectName(u"pushButton_opt")
        self.tableView = QTableView(self.page)
        self.tableView.setObjectName(u"tableView")
        self.groupBox = QGroupBox(self.page)
        self.groupBox.setObjectName(u"groupBox")
        self.textEdit_sf = QTextEdit(self.groupBox)
        self.textEdit_sf.setObjectName(u"textEdit_sf")
        self.pushButton_addsf = QPushButton(self.groupBox)
        self.pushButton_addsf.setObjectName(u"pushButton_addsf")
        self.comboBox_mdl = QComboBox(self.groupBox)
        self.comboBox_mdl.addItem("")
        self.comboBox_mdl.addItem("")
        self.comboBox_mdl.addItem("")
        self.comboBox_mdl.setObjectName(u"comboBox_mdl")
        self.lineEdit_sarea = QLineEdit(self.groupBox)
        self.lineEdit_sarea.setObjectName(u"lineEdit_sarea")
        self.lineEdit_sname = QLineEdit(self.groupBox)
        self.lineEdit_sname.setObjectName(u"lineEdit_sname")
        self.label_25 = QLabel(self.groupBox)
        self.label_25.setObjectName(u"label_25")
        self.lineEdit_smass = QLineEdit(self.groupBox)
        self.lineEdit_smass.setObjectName(u"lineEdit_smass")
        self.label_26 = QLabel(self.groupBox)
        self.label_26.setObjectName(u"label_26")
        self.label_29 = QLabel(self.groupBox)
        self.label_29.setObjectName(u"label_29")
        self.label_30 = QLabel(self.groupBox)
        self.label_30.setObjectName(u"label_30")
        self.label_31 = QLabel(self.groupBox)
        self.label_31.setObjectName(u"label_31")
        self.label_32 = QLabel(self.groupBox)
        self.label_32.setObjectName(u"label_32")
        self.pushButton_review = QPushButton(self.groupBox)
        self.pushButton_review.setObjectName(u"pushButton_review")
        self.label_33 = QLabel(self.groupBox)
        self.label_33.setObjectName(u"label_33")
        self.label_34 = QLabel(self.groupBox)
        self.label_34.setObjectName(u"label_34")
        self.checkBox_dpro = QCheckBox(self.groupBox)
        self.checkBox_dpro.setObjectName(u"checkBox_dpro")
        self.checkBox_pro = QCheckBox(self.groupBox)
        self.checkBox_pro.setObjectName(u"checkBox_pro")
        self.lineEdit_ikdp = QLineEdit(self.groupBox)
        self.lineEdit_ikdp.setObjectName(u"lineEdit_ikdp")
        self.lineEdit_dplb = QLineEdit(self.groupBox)
        self.lineEdit_dplb.setObjectName(u"lineEdit_dplb")
        self.lineEdit_dpub = QLineEdit(self.groupBox)
        self.lineEdit_dpub.setObjectName(u"lineEdit_dpub")
        self.lineEdit_ikp = QLineEdit(self.groupBox)
        self.lineEdit_ikp.setObjectName(u"lineEdit_ikp")
        self.lineEdit_plb = QLineEdit(self.groupBox)
        self.lineEdit_plb.setObjectName(u"lineEdit_plb")
        self.lineEdit_pub = QLineEdit(self.groupBox)
        self.lineEdit_pub.setObjectName(u"lineEdit_pub")
        self.label_35 = QLabel(self.groupBox)
        self.label_35.setObjectName(u"label_35")
        self.lineEdit_isite = QLineEdit(self.groupBox)
        self.lineEdit_isite.setObjectName(u"lineEdit_isite")
        self.label_36 = QLabel(self.groupBox)
        self.label_36.setObjectName(u"label_36")
        self.lineEdit_siteub = QLineEdit(self.groupBox)
        self.lineEdit_siteub.setObjectName(u"lineEdit_siteub")
        self.lineEdit_sitelb = QLineEdit(self.groupBox)
        self.lineEdit_sitelb.setObjectName(u"lineEdit_sitelb")
        self.pushButton_cls = QPushButton(self.groupBox)
        self.pushButton_cls.setObjectName(u"pushButton_cls")
        self.label_37 = QLabel(self.groupBox)
        self.label_37.setObjectName(u"label_37")
        self.lineEdit_icap = QLineEdit(self.groupBox)
        self.lineEdit_icap.setObjectName(u"lineEdit_icap")
        self.lineEdit_caplb = QLineEdit(self.groupBox)
        self.lineEdit_caplb.setObjectName(u"lineEdit_caplb")
        self.label_38 = QLabel(self.groupBox)
        self.label_38.setObjectName(u"label_38")
        self.lineEdit_capub = QLineEdit(self.groupBox)
        self.lineEdit_capub.setObjectName(u"lineEdit_capub")
        self.lineEdit_cycle = QLineEdit(self.page)
        self.lineEdit_cycle.setObjectName(u"lineEdit_cycle")
        self.label_39 = QLabel(self.page)
        self.label_39.setObjectName(u"label_39")
        self.pushButton_stp = QPushButton(self.page)
        self.pushButton_stp.setObjectName(u"pushButton_stp")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.verticalLayoutWidget = QWidget(self.page_2)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.pushButton_db_2 = QPushButton(self.page_3)
        self.pushButton_db_2.setObjectName(u"pushButton_db_2")
        self.pushButton_rd_2 = QPushButton(self.page_3)
        self.pushButton_rd_2.setObjectName(u"pushButton_rd_2")
        self.tableView_2 = QTableView(self.page_3)
        self.tableView_2.setObjectName(u"tableView_2")
        self.checkBox = QCheckBox(self.page_3)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.hide()
        self.label_data_mode = QLabel(self.page_3)
        self.label_data_mode.setObjectName(u"label_data_mode")
        self.radioButton_mode_adsorption = QRadioButton(self.page_3)
        self.radioButton_mode_adsorption.setObjectName(u"radioButton_mode_adsorption")
        self.radioButton_mode_titration = QRadioButton(self.page_3)
        self.radioButton_mode_titration.setObjectName(u"radioButton_mode_titration")
        self.groupBox_5 = QGroupBox(self.page_3)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.lineEdit_reactant = QLineEdit(self.groupBox_5)
        self.lineEdit_reactant.setObjectName(u"lineEdit_reactant")
        self.label_cs_2 = QLabel(self.groupBox_5)
        self.label_cs_2.setObjectName(u"label_cs_2")
        self.label_ph_2 = QLabel(self.groupBox_5)
        self.label_ph_2.setObjectName(u"label_ph_2")
        self.label_vol_2 = QLabel(self.groupBox_5)
        self.label_vol_2.setObjectName(u"label_vol_2")
        self.lineEdit_cs_2 = QLineEdit(self.groupBox_5)
        self.lineEdit_cs_2.setObjectName(u"lineEdit_cs_2")
        self.lineEdit_cation = QLineEdit(self.groupBox_5)
        self.lineEdit_cation.setObjectName(u"lineEdit_cation")
        self.label_cs_3 = QLabel(self.groupBox_5)
        self.label_cs_3.setObjectName(u"label_cs_3")
        self.lineEdit_anion = QLineEdit(self.groupBox_5)
        self.lineEdit_anion.setObjectName(u"lineEdit_anion")
        self.lineEdit_moles = QLineEdit(self.groupBox_5)
        self.lineEdit_moles.setObjectName(u"lineEdit_moles")
        self.label_vol_3 = QLabel(self.groupBox_5)
        self.label_vol_3.setObjectName(u"label_vol_3")
        self.label_cs_4 = QLabel(self.groupBox_5)
        self.label_cs_4.setObjectName(u"label_cs_4")
        self.lineEdit_ph_4 = QLineEdit(self.groupBox_5)
        self.lineEdit_ph_4.setObjectName(u"lineEdit_ph_4")
        self.label_initial_vol = QLabel(self.groupBox_5)
        self.label_initial_vol.setObjectName(u"label_initial_vol")
        self.lineEdit_ph_5 = QLineEdit(self.groupBox_5)
        self.lineEdit_ph_5.setObjectName(u"lineEdit_ph_5")
        self.groupBox_6 = QGroupBox(self.page_3)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.label_13 = QLabel(self.groupBox_6)
        self.label_13.setObjectName(u"label_13")
        self.radioButton_fx_2 = QRadioButton(self.groupBox_6)
        self.radioButton_fx_2.setObjectName(u"radioButton_fx_2")
        self.radioButton_ds_2 = QRadioButton(self.groupBox_6)
        self.radioButton_ds_2.setObjectName(u"radioButton_ds_2")
        self.lineEdit_base_2 = QLineEdit(self.groupBox_6)
        self.lineEdit_base_2.setObjectName(u"lineEdit_base_2")
        self.comboBox_bs_2 = QComboBox(self.groupBox_6)
        self.comboBox_bs_2.addItem("")
        self.comboBox_bs_2.addItem("")
        self.comboBox_bs_2.setObjectName(u"comboBox_bs_2")
        self.label_mix_2 = QLabel(self.groupBox_6)
        self.label_mix_2.setObjectName(u"label_mix_2")
        self.comboBox_ad_2 = QComboBox(self.groupBox_6)
        self.comboBox_ad_2.addItem("")
        self.comboBox_ad_2.addItem("")
        self.comboBox_ad_2.addItem("")
        self.comboBox_ad_2.setObjectName(u"comboBox_ad_2")
        self.lineEdit_acid_2 = QLineEdit(self.groupBox_6)
        self.lineEdit_acid_2.setObjectName(u"lineEdit_acid_2")
        self.label_16 = QLabel(self.groupBox_6)
        self.label_16.setObjectName(u"label_16")
        self.checkBox_7 = QCheckBox(self.groupBox_6)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.label_mix_5 = QLabel(self.groupBox_6)
        self.label_mix_5.setObjectName(u"label_mix_5")
        self.textEdit = QTextEdit(self.groupBox_6)
        self.textEdit.setObjectName(u"textEdit")
        self.groupBox_7 = QGroupBox(self.page_3)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.comboBox = QComboBox(self.groupBox_7)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.lineEdit_output = QLineEdit(self.groupBox_7)
        self.lineEdit_output.setObjectName(u"lineEdit_output")
        self.lineEdit_cycle_2 = QLineEdit(self.page_3)
        self.lineEdit_cycle_2.setObjectName(u"lineEdit_cycle_2")
        self.label_40 = QLabel(self.page_3)
        self.label_40.setObjectName(u"label_40")
        self.pushButton_opt_2 = QPushButton(self.page_3)
        self.pushButton_opt_2.setObjectName(u"pushButton_opt_2")
        self.label_41 = QLabel(self.page_3)
        self.label_41.setObjectName(u"label_41")
        self.pushButton_stp_2 = QPushButton(self.page_3)
        self.pushButton_stp_2.setObjectName(u"pushButton_stp_2")
        self.label_42 = QLabel(self.page_3)
        self.label_42.setObjectName(u"label_42")
        self.lineEdit_iter_2 = QLineEdit(self.page_3)
        self.lineEdit_iter_2.setObjectName(u"lineEdit_iter_2")
        self.lineEdit_temp_2 = QLineEdit(self.page_3)
        self.lineEdit_temp_2.setObjectName(u"lineEdit_temp_2")
        self.groupBox_8 = QGroupBox(self.page_3)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.textEdit_res_2 = QTextEdit(self.groupBox_8)
        self.textEdit_res_2.setObjectName(u"textEdit_res_2")
        self.groupBox_9 = QGroupBox(self.page_3)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.textEdit_sf_2 = QTextEdit(self.groupBox_9)
        self.textEdit_sf_2.setObjectName(u"textEdit_sf_2")
        self.pushButton_addsf_2 = QPushButton(self.groupBox_9)
        self.pushButton_addsf_2.setObjectName(u"pushButton_addsf_2")
        self.comboBox_mdl_2 = QComboBox(self.groupBox_9)
        self.comboBox_mdl_2.addItem("")
        self.comboBox_mdl_2.addItem("")
        self.comboBox_mdl_2.addItem("")
        self.comboBox_mdl_2.addItem("")
        self.comboBox_mdl_2.setObjectName(u"comboBox_mdl_2")
        self.lineEdit_sarea_2 = QLineEdit(self.groupBox_9)
        self.lineEdit_sarea_2.setObjectName(u"lineEdit_sarea_2")
        self.lineEdit_sname_2 = QLineEdit(self.groupBox_9)
        self.lineEdit_sname_2.setObjectName(u"lineEdit_sname_2")
        self.label_43 = QLabel(self.groupBox_9)
        self.label_43.setObjectName(u"label_43")
        self.lineEdit_smass_2 = QLineEdit(self.groupBox_9)
        self.lineEdit_smass_2.setObjectName(u"lineEdit_smass_2")
        self.label_44 = QLabel(self.groupBox_9)
        self.label_44.setObjectName(u"label_44")
        self.label_45 = QLabel(self.groupBox_9)
        self.label_45.setObjectName(u"label_45")
        self.label_46 = QLabel(self.groupBox_9)
        self.label_46.setObjectName(u"label_46")
        self.label_47 = QLabel(self.groupBox_9)
        self.label_47.setObjectName(u"label_47")
        self.label_48 = QLabel(self.groupBox_9)
        self.label_48.setObjectName(u"label_48")
        self.pushButton_addreact = QPushButton(self.groupBox_9)
        self.pushButton_addreact.setObjectName(u"pushButton_addreact")
        self.label_49 = QLabel(self.groupBox_9)
        self.label_49.setObjectName(u"label_49")
        self.label_50 = QLabel(self.groupBox_9)
        self.label_50.setObjectName(u"label_50")
        self.label_51 = QLabel(self.groupBox_9)
        self.label_51.setObjectName(u"label_51")
        self.lineEdit_reaction = QLineEdit(self.groupBox_9)
        self.lineEdit_reaction.setObjectName(u"lineEdit_reaction")
        self.lineEdit_siteub_2 = QLineEdit(self.groupBox_9)
        self.lineEdit_siteub_2.setObjectName(u"lineEdit_siteub_2")
        self.lineEdit_isite_2 = QLineEdit(self.groupBox_9)
        self.lineEdit_isite_2.setObjectName(u"lineEdit_isite_2")
        self.lineEdit_sitelb_2 = QLineEdit(self.groupBox_9)
        self.lineEdit_sitelb_2.setObjectName(u"lineEdit_sitelb_2")
        self.checkBox_site = QCheckBox(self.groupBox_9)
        self.checkBox_site.setObjectName(u"checkBox_site")
        self.checkBox_c1 = QCheckBox(self.groupBox_9)
        self.checkBox_c1.setObjectName(u"checkBox_c1")
        self.checkBox_c2 = QCheckBox(self.groupBox_9)
        self.checkBox_c2.setObjectName(u"checkBox_c2")
        self.checkBox_logk = QCheckBox(self.groupBox_9)
        self.checkBox_logk.setObjectName(u"checkBox_logk")
        self.lineEdit_ic1 = QLineEdit(self.groupBox_9)
        self.lineEdit_ic1.setObjectName(u"lineEdit_ic1")
        self.lineEdit_ic2 = QLineEdit(self.groupBox_9)
        self.lineEdit_ic2.setObjectName(u"lineEdit_ic2")
        self.lineEdit_ik = QLineEdit(self.groupBox_9)
        self.lineEdit_ik.setObjectName(u"lineEdit_ik")
        self.lineEdit_ic1ub = QLineEdit(self.groupBox_9)
        self.lineEdit_ic1ub.setObjectName(u"lineEdit_ic1ub")
        self.lineEdit_ic1lb = QLineEdit(self.groupBox_9)
        self.lineEdit_ic1lb.setObjectName(u"lineEdit_ic1lb")
        self.lineEdit_ic2lb = QLineEdit(self.groupBox_9)
        self.lineEdit_ic2lb.setObjectName(u"lineEdit_ic2lb")
        self.lineEdit_ic2ub = QLineEdit(self.groupBox_9)
        self.lineEdit_ic2ub.setObjectName(u"lineEdit_ic2ub")
        self.lineEdit_iklb = QLineEdit(self.groupBox_9)
        self.lineEdit_iklb.setObjectName(u"lineEdit_iklb")
        self.lineEdit_ikub = QLineEdit(self.groupBox_9)
        self.lineEdit_ikub.setObjectName(u"lineEdit_ikub")
        self.comboBox_charge = QComboBox(self.groupBox_9)
        self.comboBox_charge.addItem("")
        self.comboBox_charge.addItem("")
        self.comboBox_charge.setObjectName(u"comboBox_charge")
        self.checkBox_z1 = QCheckBox(self.groupBox_9)
        self.checkBox_z1.setObjectName(u"checkBox_z1")
        self.label_52 = QLabel(self.groupBox_9)
        self.label_52.setObjectName(u"label_52")
        self.lineEdit_iz1 = QLineEdit(self.groupBox_9)
        self.lineEdit_iz1.setObjectName(u"lineEdit_iz1")
        self.lineEdit_iz1lb = QLineEdit(self.groupBox_9)
        self.lineEdit_iz1lb.setObjectName(u"lineEdit_iz1lb")
        self.lineEdit_iz1ub = QLineEdit(self.groupBox_9)
        self.lineEdit_iz1ub.setObjectName(u"lineEdit_iz1ub")
        self.lineEdit_totalz = QLineEdit(self.groupBox_9)
        self.lineEdit_totalz.setObjectName(u"lineEdit_totalz")
        self.pushButton_delreact = QPushButton(self.groupBox_9)
        self.pushButton_delreact.setObjectName(u"pushButton_delreact")
        self.pushButton_delsf = QPushButton(self.groupBox_9)
        self.pushButton_delsf.setObjectName(u"pushButton_delsf")
        self.pushButton_cls_4 = QPushButton(self.groupBox_9)
        self.pushButton_cls_4.setObjectName(u"pushButton_cls_4")
        self.lineEdit_sformula = QLineEdit(self.groupBox_9)
        self.lineEdit_sformula.setObjectName(u"lineEdit_sformula")
        self.label_53 = QLabel(self.groupBox_9)
        self.label_53.setObjectName(u"label_53")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menuTitration = QMenu(self.menubar)
        self.menuTitration.setObjectName(u"menuTitration")
        self.menuAlgorithm = QMenu(self.menubar)
        self.menuAlgorithm.setObjectName(u"menuAlgorithm")
        self.menuDirectory = QMenu(self.menubar)
        self.menuDirectory.setObjectName(u"menuDirectory")
        self.menuInit_protonation = QMenu(self.menubar)
        self.menuInit_protonation.setObjectName(u"menuInit_protonation")
        self.menuHistory = QMenu(self.menubar)
        self.menuHistory.setObjectName(u"menuHistory")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuTitration.menuAction())
        self.menubar.addAction(self.menuAlgorithm.menuAction())
        self.menubar.addAction(self.menuDirectory.menuAction())
        self.menubar.addAction(self.menuInit_protonation.menuAction())
        self.menubar.addAction(self.menuHistory.menuAction())
        self.menuTitration.addAction(self.actionTitration)
        self.menuTitration.addAction(self.actionPlot)
        self.menuTitration.addAction(self.actionAdvanced)
        self.menuAlgorithm.addAction(self.actiondifferential_evolution)
        self.menuAlgorithm.addAction(self.actionDual_annealing)
        self.menuAlgorithm.addAction(self.actionnelder_mead)
        self.menuDirectory.addAction(self.actionDatabase_folder)
        self.menuDirectory.addAction(self.actionData_folder)
        self.menuDirectory.addAction(self.actionOutput_folder)
        self.menuInit_protonation.addAction(self.actionDisabled)
        self.menuInit_protonation.addAction(self.actionEnabled)
        self.menuHistory.addAction(self.actionSave_settings)
        self.menuHistory.addAction(self.actionLoad_settings)
        self.menuHistory.addSeparator()
        self.menuHistory.addAction(self.actionCompare_results)
        self.menuHistory.addAction(self.actionOpen_output_folder)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)

        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"PhreeFit", None))
        self.actionDatabase_path.setText(QCoreApplication.translate("MainWindow", u"Database path", None))
        self.actionparameters.setText(QCoreApplication.translate("MainWindow", u"Parameters", None))
        self.actionpp.setText(QCoreApplication.translate("MainWindow", u"pp", None))
        self.actionTitration.setText(QCoreApplication.translate("MainWindow", u"Titration", None))
        self.actionPlot.setText(QCoreApplication.translate("MainWindow", u"Plot", None))
        self.actionAdvanced.setText(QCoreApplication.translate("MainWindow", u"Advanced", None))
        self.actiondifferential_evolution.setText(
            QCoreApplication.translate("MainWindow", u"Differential evolution", None))
        self.actionDual_annealing.setText(QCoreApplication.translate("MainWindow", u"Dual annealing", None))
        self.actionnelder_mead.setText(QCoreApplication.translate("MainWindow", u"Nelder Mead", None))
        self.actionDatabase_folder.setText(QCoreApplication.translate("MainWindow", u"Database path", None))
        self.actionOutput_folder.setText(QCoreApplication.translate("MainWindow", u"Output path", None))
        self.actionDisabled.setText(QCoreApplication.translate("MainWindow", u"Disabled", None))
        # self.actionpH_2.setText(QCoreApplication.translate("MainWindow", u"pH", None))
        # self.actionIS_2.setText(QCoreApplication.translate("MainWindow", u"IS", None))
        self.actionEnabled.setText(QCoreApplication.translate("MainWindow", u"Enabled", None))
        self.actionData_folder.setText(QCoreApplication.translate("MainWindow", u"Data path", None))
        self.actionSave_settings.setText(QCoreApplication.translate("MainWindow", u"Save settings", None))
        self.actionLoad_settings.setText(QCoreApplication.translate("MainWindow", u"Load settings", None))
        self.actionCompare_results.setText(QCoreApplication.translate("MainWindow", u"Compare results", None))
        self.actionOpen_output_folder.setText(QCoreApplication.translate("MainWindow", u"Open output folder", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"T", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Max iter:", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Titration solution", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"mol/L", None))
        self.radioButton_fx.setText(QCoreApplication.translate("MainWindow", u"Fix pH", None))
        self.radioButton_ds.setText(QCoreApplication.translate("MainWindow", u"Dissolution", None))
        self.comboBox_bs.setItemText(0, QCoreApplication.translate("MainWindow", u"NaOH", None))
        self.comboBox_bs.setItemText(1, QCoreApplication.translate("MainWindow", u"KOH", None))

        self.label_mix.setText(QCoreApplication.translate("MainWindow", u"Solution type", None))
        self.comboBox_ad.setItemText(0, QCoreApplication.translate("MainWindow", u"HCl", None))
        self.comboBox_ad.setItemText(1, QCoreApplication.translate("MainWindow", u"HNO3", None))

        self.label_15.setText(QCoreApplication.translate("MainWindow", u"mol/L", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Initial Solution", None))
        self.label_cs.setText(QCoreApplication.translate("MainWindow", u"IS mol/L", None))
        self.label_ph.setText(QCoreApplication.translate("MainWindow", u"Initial pH", None))
        self.label_vol.setText(QCoreApplication.translate("MainWindow", u"Initial volume mL", None))
        self.pushButton_db.setText(QCoreApplication.translate("MainWindow", u"Database", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Results", None))
        self.pushButton_rd.setText(QCoreApplication.translate("MainWindow", u"Read Titration data", None))
        self.pushButton_opt.setText(QCoreApplication.translate("MainWindow", u"Optimize", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Set Surface parameters", None))
        self.pushButton_addsf.setText(QCoreApplication.translate("MainWindow", u"Add surface", None))
        self.comboBox_mdl.setItemText(0, QCoreApplication.translate("MainWindow", u"NEM", None))
        self.comboBox_mdl.setItemText(1, QCoreApplication.translate("MainWindow", u"CCM", None))
        self.comboBox_mdl.setItemText(2, QCoreApplication.translate("MainWindow", u"GDDL", None))

        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Surface name", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Surface area", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"m2/g", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Surface mass", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"g", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Surface model", None))
        self.pushButton_review.setText(QCoreApplication.translate("MainWindow", u"Review reactions", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Initial Logk", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"LogK bounds", None))
        self.checkBox_dpro.setText(QCoreApplication.translate("MainWindow", u"Acidic site", None))
        self.checkBox_pro.setText(QCoreApplication.translate("MainWindow", u"Basic site", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Site (mole)", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Bounds", None))
        self.pushButton_cls.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Capacitance (F/m2)", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Bounds", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Cores", None))
        self.pushButton_stp.setText(QCoreApplication.translate("MainWindow", u"Terminate", None))
        self.pushButton_db_2.setText(QCoreApplication.translate("MainWindow", u"Database", None))
        self.pushButton_rd_2.setText(QCoreApplication.translate("MainWindow", u"Read exp data", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Titration", None))
        self.label_data_mode.setText(QCoreApplication.translate("MainWindow", u"Mode:", None))
        self.radioButton_mode_adsorption.setText(QCoreApplication.translate("MainWindow", u"Adsorption", None))
        self.radioButton_mode_titration.setText(QCoreApplication.translate("MainWindow", u"Titration", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Initial Solution", None))
        self.label_cs_2.setText(QCoreApplication.translate("MainWindow", u"Cation", None))
        self.label_ph_2.setText(QCoreApplication.translate("MainWindow", u"Conc (mol/L)", None))
        self.label_vol_2.setText(QCoreApplication.translate("MainWindow", u"Reactant", None))
        self.label_cs_3.setText(QCoreApplication.translate("MainWindow", u"Anion", None))
        self.label_vol_3.setText(QCoreApplication.translate("MainWindow", u"mol/L", None))
        self.label_cs_4.setText(QCoreApplication.translate("MainWindow", u"Initial pH", None))
        self.label_initial_vol.setText(QCoreApplication.translate("MainWindow", u"V (mL)", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Equilibrium or Titration solution", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"mol/L", None))
        self.radioButton_fx_2.setText(QCoreApplication.translate("MainWindow", u"Fix pH", None))
        self.radioButton_ds_2.setText(QCoreApplication.translate("MainWindow", u"Dissolve", None))
        self.comboBox_bs_2.setItemText(0, QCoreApplication.translate("MainWindow", u"NaOH", None))
        self.comboBox_bs_2.setItemText(1, QCoreApplication.translate("MainWindow", u"KOH", None))

        self.label_mix_2.setText(QCoreApplication.translate("MainWindow", u"Type", None))
        self.comboBox_ad_2.setItemText(0, QCoreApplication.translate("MainWindow", u"HCl", None))
        self.comboBox_ad_2.setItemText(1, QCoreApplication.translate("MainWindow", u"H2SO4", None))
        self.comboBox_ad_2.setItemText(2, QCoreApplication.translate("MainWindow", u"HNO3", None))

        self.label_16.setText(QCoreApplication.translate("MainWindow", u"mol/L", None))
        self.checkBox_7.setText(QCoreApplication.translate("MainWindow", u"Automatic pH", None))
        self.label_mix_5.setText(QCoreApplication.translate("MainWindow", u"Eq Phase:", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Output", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"totals", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"activities", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"molalities ", None))

        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Cores", None))
        self.pushButton_opt_2.setText(QCoreApplication.translate("MainWindow", u"Optimize", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"T", None))
        self.pushButton_stp_2.setText(QCoreApplication.translate("MainWindow", u"Terminate", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Max iter:", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Results", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Set Surface parameters", None))
        self.pushButton_addsf_2.setText(QCoreApplication.translate("MainWindow", u"Add surface", None))
        self.comboBox_mdl_2.setItemText(0, QCoreApplication.translate("MainWindow", u"NEM", None))
        self.comboBox_mdl_2.setItemText(1, QCoreApplication.translate("MainWindow", u"CCM", None))
        self.comboBox_mdl_2.setItemText(2, QCoreApplication.translate("MainWindow", u"GDDL", None))
        self.comboBox_mdl_2.setItemText(3, QCoreApplication.translate("MainWindow", u"CDMUSIC", None))

        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Surface name", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Surface area", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"m2/g", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"Surface mass", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"g", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"Model selection", None))
        self.pushButton_addreact.setText(QCoreApplication.translate("MainWindow", u"Add reaction", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"Initial value", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"Bounds", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"Reaction", None))
        self.lineEdit_reaction.setText("")
        self.checkBox_site.setText(QCoreApplication.translate("MainWindow", u"Site (moles)", None))
        self.checkBox_c1.setText(QCoreApplication.translate("MainWindow", u"C1 (F/m2)", None))
        self.checkBox_c2.setText(QCoreApplication.translate("MainWindow", u"C2 (F/m2)", None))
        self.checkBox_logk.setText(QCoreApplication.translate("MainWindow", u"   log_k", None))
        self.comboBox_charge.setItemText(0, QCoreApplication.translate("MainWindow", u"z0+z1", None))
        self.comboBox_charge.setItemText(1, QCoreApplication.translate("MainWindow", u"z1+zd", None))

        self.checkBox_z1.setText(QCoreApplication.translate("MainWindow", u"   z1", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"Fix", None))
        self.pushButton_delreact.setText(QCoreApplication.translate("MainWindow", u"Del reaction", None))
        self.pushButton_delsf.setText(QCoreApplication.translate("MainWindow", u"Del surface", None))
        self.pushButton_cls_4.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"Formula", None))
        self.menuTitration.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuAlgorithm.setTitle(QCoreApplication.translate("MainWindow", u"Algorithm", None))
        self.menuDirectory.setTitle(QCoreApplication.translate("MainWindow", u"Directory", None))
        self.menuInit_protonation.setTitle(QCoreApplication.translate("MainWindow", u"Pre-equilibrate", None))
        self.menuHistory.setTitle(QCoreApplication.translate("MainWindow", u"History", None))
        # retranslateUi
        self.lineEdit_ikp.setText("0")
        self.lineEdit_ikdp.setText("0")
        self.lineEdit_dplb.setText("-10")
        self.lineEdit_dpub.setText("10")
        self.lineEdit_plb.setText("-10")
        self.lineEdit_pub.setText("10")
        self.lineEdit_isite.setText("0.0001")
        self.lineEdit_siteub.setText("0.01")
        self.lineEdit_sitelb.setText("0")
        self.lineEdit_iter.setText("1000")
        self.lineEdit_temp.setText("6000")
        self.radioButton_ds.setChecked(True)
        self.radioButton_ds_2.setChecked(True)
        self.lineEdit_icap.setText("1")
        self.lineEdit_caplb.setText("0")
        self.lineEdit_capub.setText("5")
        self.lineEdit_cycle.setText("1")
        self.pushButton_stp.setEnabled(False)
        self.lineEdit_base.setText("0")
        self.lineEdit_acid.setText("0")
        self.lineEdit_temp.setValidator(QIntValidator())
        self.lineEdit_iter.setValidator(QIntValidator())
        self.lineEdit_sarea.setValidator(QDoubleValidator())
        self.lineEdit_smass.setValidator(QDoubleValidator())
        self.lineEdit_cs.setValidator(QDoubleValidator())
        self.lineEdit_vol.setValidator(QDoubleValidator())
        self.lineEdit_ph.setValidator(QDoubleValidator())
        self.textEdit_sf.setReadOnly(True)
        self.textEdit_res.setReadOnly(True)
        self.lineEdit_ik.setText("0")
        self.lineEdit_iklb.setText("-10")
        self.lineEdit_ikub.setText("10")
        self.lineEdit_isite_2.setText("0.0001")
        self.lineEdit_sitelb_2.setText("0")
        self.lineEdit_siteub_2.setText("0.01")
        self.lineEdit_ic1.setText("1")
        self.lineEdit_ic1lb.setText("0")
        self.lineEdit_ic1ub.setText("5")
        self.lineEdit_ic2.setText("1")
        self.lineEdit_ic2lb.setText("0")
        self.lineEdit_ic2ub.setText("1")
        self.lineEdit_iter_2.setText("1000")
        self.lineEdit_temp_2.setText("6000")
        self.radioButton_ds.setChecked(True)
        self.lineEdit_iz1.setText("1")
        self.lineEdit_iz1lb.setText("-1")
        self.lineEdit_iz1ub.setText("1")
        self.lineEdit_totalz.setText("1")
        self.lineEdit_cycle_2.setText("1")
        self.pushButton_stp_2.setEnabled(False)
        self.radioButton_mode_adsorption.setChecked(True)
        self.lineEdit_base_2.setText("0")
        self.lineEdit_acid_2.setText("0")
        self.lineEdit_ph_5.setText("1000")
        self.checkBox_logk.setChecked(True)
        self.checkBox_site.setChecked(True)
        self.checkBox_c1.setChecked(True)
        self.checkBox_c2.setChecked(True)
        self.checkBox_z1.setChecked(True)
        self.lineEdit_temp_2.setValidator(QIntValidator())
        self.lineEdit_cycle.setValidator(QIntValidator())
        self.lineEdit_cycle_2.setValidator(QIntValidator())
        self.lineEdit_iter_2.setValidator(QIntValidator())
        self.lineEdit_sarea_2.setValidator(QDoubleValidator())
        self.lineEdit_smass_2.setValidator(QDoubleValidator())
        self.lineEdit_cs_2.setValidator(QDoubleValidator())
        self.lineEdit_ph_4.setValidator(QDoubleValidator())
        self.lineEdit_ph_5.setValidator(QDoubleValidator())


class MainWindowLayoutManager(QObject):
    """Install native Qt layouts without changing the public widget names."""

    def __init__(self, window):
        super().__init__(window)
        self.window = window
        self._install_root_layout()
        self._install_titration_layout()
        self._install_plot_layout()
        self._install_advanced_layout()
        self._configure_shared_widgets()
        window.setMinimumSize(760, 580)

    @staticmethod
    def _margins(layout, value=8, spacing=6):
        layout.setContentsMargins(value, value, value, value)
        layout.setSpacing(spacing)
        return layout

    @staticmethod
    def _scroll_for(widget, minimum_width=220):
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setWidget(widget)
        scroll.setMinimumWidth(minimum_width)
        return scroll

    def _install_root_layout(self):
        layout = QVBoxLayout(self.window.centralwidget)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)
        layout.addWidget(self.window.stackedWidget)

    def _install_plot_layout(self):
        layout = self._margins(QVBoxLayout(self.window.page_2))
        layout.addWidget(self.window.verticalLayoutWidget)

    def _install_titration_layout(self):
        w = self.window
        page_layout = self._margins(QVBoxLayout(w.page))
        outer_splitter = QSplitter(Qt.Orientation.Horizontal)
        outer_splitter.setChildrenCollapsible(False)
        content_splitter = QSplitter(Qt.Orientation.Horizontal)
        content_splitter.setChildrenCollapsible(False)

        data_panel = QWidget()
        data_layout = self._margins(QVBoxLayout(data_panel), 0)
        w.pushButton_db.setMinimumSize(200, 54)
        w.pushButton_rd.setMinimumSize(200, 54)
        data_layout.addWidget(w.pushButton_db)
        data_layout.addWidget(w.pushButton_rd)
        data_layout.addWidget(w.tableView, 1)

        settings_panel = QWidget()
        settings_layout = self._margins(QVBoxLayout(settings_panel), 4)
        initial_layout = self._margins(QFormLayout(w.groupBox_3))
        initial_layout.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.AllNonFixedFieldsGrow)
        initial_layout.addRow(w.label_cs, w.lineEdit_cs)
        initial_layout.addRow(w.label_ph, w.lineEdit_ph)
        initial_layout.addRow(w.label_vol, w.lineEdit_vol)

        solution_layout = self._margins(QGridLayout(w.groupBox_2))
        solution_layout.addWidget(w.label_mix, 0, 0)
        solution_layout.addWidget(w.radioButton_fx, 0, 1)
        solution_layout.addWidget(w.radioButton_ds, 0, 2)
        solution_layout.addWidget(w.comboBox_bs, 1, 0)
        solution_layout.addWidget(w.lineEdit_base, 1, 1)
        solution_layout.addWidget(w.label_12, 1, 2)
        solution_layout.addWidget(w.comboBox_ad, 2, 0)
        solution_layout.addWidget(w.lineEdit_acid, 2, 1)
        solution_layout.addWidget(w.label_15, 2, 2)
        solution_layout.setColumnStretch(1, 1)

        w.groupBox_run = QGroupBox("Optimization")
        run_layout = self._margins(QGridLayout(w.groupBox_run))
        run_layout.addWidget(w.label_27, 0, 0)
        run_layout.addWidget(w.lineEdit_iter, 0, 1)
        run_layout.addWidget(w.label_28, 1, 0)
        run_layout.addWidget(w.lineEdit_temp, 1, 1)
        run_layout.addWidget(w.label_39, 2, 0)
        run_layout.addWidget(w.lineEdit_cycle, 2, 1)
        w.pushButton_opt.setMinimumSize(150, 84)
        run_layout.addWidget(w.pushButton_opt, 0, 2, 3, 1)
        w.pushButton_sensitivity = QPushButton("Sensitivity", w.groupBox_run)
        w.pushButton_sensitivity.setObjectName("pushButton_sensitivity")
        w.pushButton_sensitivity.setMinimumHeight(36)
        run_layout.addWidget(w.pushButton_sensitivity, 3, 0, 1, 2)
        run_layout.addWidget(w.pushButton_stp, 3, 2)
        run_layout.setColumnStretch(1, 1)

        settings_layout.addWidget(w.groupBox_3)
        settings_layout.addWidget(w.groupBox_2)
        settings_layout.addWidget(w.groupBox)
        settings_layout.addStretch()

        self._install_titration_surface_grid()
        review_group = QGroupBox("Current species and reactions")
        review_group.setObjectName("groupBox_surface_review_titration")
        review_layout = self._margins(QVBoxLayout(review_group), 4)
        w.textEdit_sf.setMinimumHeight(220)
        review_layout.addWidget(w.textEdit_sf)

        right_panel = QWidget()
        right_layout = self._margins(QVBoxLayout(right_panel), 0)
        right_layout.addWidget(review_group, 1)
        right_layout.addWidget(w.groupBox_run)
        w.groupBox_surface_review_titration = review_group
        content_splitter.addWidget(self._scroll_for(settings_panel, 300))
        content_splitter.addWidget(right_panel)
        content_splitter.setStretchFactor(0, 4)
        content_splitter.setStretchFactor(1, 3)
        content_splitter.setSizes([480, 380])

        results_layout = self._margins(QVBoxLayout(w.groupBox_4), 4)
        results_layout.addWidget(w.textEdit_res)
        w.groupBox_4.setMinimumHeight(105)
        content_panel = QWidget()
        content_layout = self._margins(QVBoxLayout(content_panel), 0)
        content_layout.addWidget(content_splitter, 1)
        content_layout.addWidget(w.groupBox_4)

        outer_splitter.addWidget(data_panel)
        outer_splitter.addWidget(content_panel)
        outer_splitter.setStretchFactor(0, 1)
        outer_splitter.setStretchFactor(1, 4)
        outer_splitter.setSizes([230, 870])
        page_layout.addWidget(outer_splitter, 1)
        w.titration_splitter = outer_splitter
        w.titration_content_splitter = content_splitter

    def _install_titration_surface_grid(self):
        w = self.window
        layout = self._margins(QGridLayout(w.groupBox))
        layout.addWidget(w.label_25, 0, 0)
        layout.addWidget(w.lineEdit_sname, 0, 1, 1, 2)
        layout.addWidget(w.label_26, 1, 0)
        layout.addWidget(w.lineEdit_sarea, 1, 1, 1, 2)
        layout.addWidget(w.label_29, 1, 3)
        layout.addWidget(w.label_30, 2, 0)
        layout.addWidget(w.lineEdit_smass, 2, 1, 1, 2)
        layout.addWidget(w.label_31, 2, 3)
        layout.addWidget(w.label_32, 3, 0)
        layout.addWidget(w.comboBox_mdl, 3, 1, 1, 2)

        w.label_33.setText("Initial")
        w.label_34.setText("Bounds")
        layout.addWidget(w.label_33, 4, 1)
        layout.addWidget(w.label_34, 4, 2, 1, 2, Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(w.checkBox_dpro, 5, 0)
        layout.addWidget(w.lineEdit_ikdp, 5, 1)
        layout.addWidget(w.lineEdit_dplb, 5, 2)
        layout.addWidget(w.lineEdit_dpub, 5, 3)
        layout.addWidget(w.checkBox_pro, 6, 0)
        layout.addWidget(w.lineEdit_ikp, 6, 1)
        layout.addWidget(w.lineEdit_plb, 6, 2)
        layout.addWidget(w.lineEdit_pub, 6, 3)
        layout.addWidget(w.label_35, 7, 0)
        layout.addWidget(w.lineEdit_isite, 7, 1)
        layout.addWidget(w.lineEdit_sitelb, 7, 2)
        layout.addWidget(w.lineEdit_siteub, 7, 3)
        layout.addWidget(w.label_37, 8, 0)
        layout.addWidget(w.lineEdit_icap, 8, 1)
        layout.addWidget(w.lineEdit_caplb, 8, 2)
        layout.addWidget(w.lineEdit_capub, 8, 3)
        w.label_36.hide()
        w.label_38.hide()

        button_layout = QHBoxLayout()
        button_layout.addWidget(w.pushButton_addsf)
        button_layout.addWidget(w.pushButton_review)
        button_layout.addWidget(w.pushButton_cls)
        layout.addLayout(button_layout, 9, 0, 1, 4)
        for column in (1, 2, 3):
            layout.setColumnStretch(column, 1)

    def _install_advanced_layout(self):
        w = self.window
        page_layout = self._margins(QVBoxLayout(w.page_3))
        outer_splitter = QSplitter(Qt.Orientation.Horizontal)
        outer_splitter.setChildrenCollapsible(False)
        content_splitter = QSplitter(Qt.Orientation.Horizontal)
        content_splitter.setChildrenCollapsible(False)

        data_panel = QWidget()
        data_layout = self._margins(QVBoxLayout(data_panel), 0)
        w.pushButton_db_2.setMinimumSize(200, 54)
        w.pushButton_rd_2.setMinimumSize(200, 54)
        data_layout.addWidget(w.pushButton_db_2)
        data_layout.addWidget(w.pushButton_rd_2)
        mode_layout = QGridLayout()
        mode_layout.addWidget(w.label_data_mode, 0, 0, 2, 1)
        mode_layout.addWidget(w.radioButton_mode_adsorption, 0, 1)
        mode_layout.addWidget(w.radioButton_mode_titration, 1, 1)
        data_layout.addLayout(mode_layout)
        data_layout.addWidget(w.tableView_2, 1)

        settings_panel = QWidget()
        settings_layout = self._margins(QVBoxLayout(settings_panel), 4)
        self._install_advanced_solution_groups()
        w.groupBox_run_2 = QGroupBox("Optimization")
        run_layout = self._margins(QGridLayout(w.groupBox_run_2))
        run_layout.addWidget(w.label_42, 0, 0)
        run_layout.addWidget(w.lineEdit_iter_2, 0, 1)
        run_layout.addWidget(w.label_41, 1, 0)
        run_layout.addWidget(w.lineEdit_temp_2, 1, 1)
        run_layout.addWidget(w.label_40, 2, 0)
        run_layout.addWidget(w.lineEdit_cycle_2, 2, 1)
        w.pushButton_opt_2.setMinimumSize(150, 84)
        run_layout.addWidget(w.pushButton_opt_2, 0, 2, 3, 1)
        w.pushButton_sensitivity_2 = QPushButton("Sensitivity", w.groupBox_run_2)
        w.pushButton_sensitivity_2.setObjectName("pushButton_sensitivity_2")
        w.pushButton_sensitivity_2.setMinimumHeight(36)
        run_layout.addWidget(w.pushButton_sensitivity_2, 3, 0, 1, 2)
        run_layout.addWidget(w.pushButton_stp_2, 3, 2)
        run_layout.setColumnStretch(1, 1)
        settings_layout.addWidget(w.groupBox_5)
        settings_layout.addWidget(w.groupBox_6)
        settings_layout.addWidget(w.groupBox_7)
        settings_layout.addWidget(w.groupBox_9)
        settings_layout.addStretch()

        self._install_advanced_surface_grid()
        review_group = QGroupBox("Current species and reactions")
        review_group.setObjectName("groupBox_surface_review")
        review_layout = self._margins(QVBoxLayout(review_group), 4)
        w.textEdit_sf_2.setMinimumHeight(220)
        review_layout.addWidget(w.textEdit_sf_2)

        right_panel = QWidget()
        right_layout = self._margins(QVBoxLayout(right_panel), 0)
        right_layout.addWidget(review_group, 1)
        right_layout.addWidget(w.groupBox_run_2)
        w.groupBox_surface_review = review_group
        content_splitter.addWidget(self._scroll_for(settings_panel, 250))
        content_splitter.addWidget(right_panel)
        content_splitter.setStretchFactor(0, 4)
        content_splitter.setStretchFactor(1, 3)
        content_splitter.setSizes([480, 380])

        results_layout = self._margins(QVBoxLayout(w.groupBox_8), 4)
        results_layout.addWidget(w.textEdit_res_2)
        w.groupBox_8.setMinimumHeight(100)
        content_panel = QWidget()
        content_layout = self._margins(QVBoxLayout(content_panel), 0)
        content_layout.addWidget(content_splitter, 1)
        content_layout.addWidget(w.groupBox_8)

        outer_splitter.addWidget(data_panel)
        outer_splitter.addWidget(content_panel)
        outer_splitter.setStretchFactor(0, 1)
        outer_splitter.setStretchFactor(1, 4)
        outer_splitter.setSizes([230, 870])
        page_layout.addWidget(outer_splitter, 1)
        w.advanced_splitter = outer_splitter
        w.advanced_content_splitter = content_splitter

    def _install_advanced_solution_groups(self):
        w = self.window
        initial_layout = self._margins(QGridLayout(w.groupBox_5))
        initial_layout.addWidget(w.label_cs_4, 0, 0)
        initial_layout.addWidget(w.lineEdit_ph_4, 0, 1)
        initial_layout.addWidget(w.label_initial_vol, 0, 2)
        initial_layout.addWidget(w.lineEdit_ph_5, 0, 3)
        initial_layout.addWidget(w.label_cs_2, 1, 0)
        initial_layout.addWidget(w.lineEdit_cation, 1, 1)
        initial_layout.addWidget(w.label_cs_3, 1, 2)
        initial_layout.addWidget(w.lineEdit_anion, 1, 3)
        initial_layout.addWidget(w.label_ph_2, 2, 0)
        initial_layout.addWidget(w.lineEdit_cs_2, 2, 1, 1, 3)
        initial_layout.addWidget(w.label_vol_2, 3, 0)
        initial_layout.addWidget(w.lineEdit_reactant, 3, 1)
        initial_layout.addWidget(w.lineEdit_moles, 3, 2)
        initial_layout.addWidget(w.label_vol_3, 3, 3)
        initial_layout.setColumnStretch(1, 1)
        initial_layout.setColumnStretch(3, 1)

        solution_layout = self._margins(QGridLayout(w.groupBox_6))
        solution_layout.addWidget(w.label_mix_2, 0, 0)
        solution_layout.addWidget(w.radioButton_fx_2, 0, 1)
        solution_layout.addWidget(w.radioButton_ds_2, 0, 2)
        solution_layout.addWidget(w.checkBox_7, 1, 0, 1, 3)
        solution_layout.addWidget(w.comboBox_bs_2, 2, 0)
        solution_layout.addWidget(w.lineEdit_base_2, 2, 1)
        solution_layout.addWidget(w.label_13, 2, 2)
        solution_layout.addWidget(w.comboBox_ad_2, 3, 0)
        solution_layout.addWidget(w.lineEdit_acid_2, 3, 1)
        solution_layout.addWidget(w.label_16, 3, 2)
        solution_layout.addWidget(w.label_mix_5, 4, 0)
        solution_layout.addWidget(w.textEdit, 4, 1, 1, 2)
        solution_layout.setColumnStretch(1, 1)

        output_layout = self._margins(QHBoxLayout(w.groupBox_7))
        output_layout.addWidget(w.comboBox)
        output_layout.addWidget(w.lineEdit_output, 1)

    def _install_advanced_surface_grid(self):
        w = self.window
        layout = self._margins(QGridLayout(w.groupBox_9))
        layout.addWidget(w.label_43, 0, 0)
        layout.addWidget(w.lineEdit_sname_2, 0, 1)
        layout.addWidget(w.label_53, 0, 2)
        layout.addWidget(w.lineEdit_sformula, 0, 3)
        layout.addWidget(w.label_44, 1, 0)
        layout.addWidget(w.lineEdit_sarea_2, 1, 1, 1, 2)
        layout.addWidget(w.label_45, 1, 3)
        layout.addWidget(w.label_46, 2, 0)
        layout.addWidget(w.lineEdit_smass_2, 2, 1, 1, 2)
        layout.addWidget(w.label_47, 2, 3)
        layout.addWidget(w.label_48, 3, 0)
        layout.addWidget(w.comboBox_mdl_2, 3, 1)
        layout.addWidget(w.pushButton_addsf_2, 3, 2)
        layout.addWidget(w.pushButton_delsf, 3, 3)
        layout.addWidget(w.label_51, 4, 0)
        layout.addWidget(w.lineEdit_reaction, 4, 1, 1, 3)

        w.label_52.setText("Fixed / Parameter")
        w.label_49.setText("Initial")
        w.label_50.setText("Bounds")
        layout.addWidget(w.label_52, 5, 0)
        layout.addWidget(w.label_49, 5, 1)
        layout.addWidget(w.label_50, 5, 2, 1, 2, Qt.AlignmentFlag.AlignCenter)
        parameter_rows = (
            (w.checkBox_site, w.lineEdit_isite_2, w.lineEdit_sitelb_2, w.lineEdit_siteub_2),
            (w.checkBox_c1, w.lineEdit_ic1, w.lineEdit_ic1lb, w.lineEdit_ic1ub),
            (w.checkBox_c2, w.lineEdit_ic2, w.lineEdit_ic2lb, w.lineEdit_ic2ub),
            (w.checkBox_logk, w.lineEdit_ik, w.lineEdit_iklb, w.lineEdit_ikub),
            (w.checkBox_z1, w.lineEdit_iz1, w.lineEdit_iz1lb, w.lineEdit_iz1ub),
        )
        for row, widgets in enumerate(parameter_rows, start=6):
            for column, widget in enumerate(widgets):
                layout.addWidget(widget, row, column)

        w.label_charge_location = QLabel("Charge location")
        w.label_charge_location.setObjectName("label_charge_location")
        w.label_total_charge = QLabel("Total charge")
        w.label_total_charge.setObjectName("label_total_charge")
        layout.addWidget(w.label_charge_location, 11, 0)
        layout.addWidget(w.comboBox_charge, 11, 1)
        layout.addWidget(w.label_total_charge, 11, 2)
        layout.addWidget(w.lineEdit_totalz, 11, 3)

        button_layout = QHBoxLayout()
        button_layout.addWidget(w.pushButton_addreact)
        button_layout.addWidget(w.pushButton_delreact)
        button_layout.addWidget(w.pushButton_cls_4)
        layout.addLayout(button_layout, 12, 0, 1, 4)
        for column in (1, 2, 3):
            layout.setColumnStretch(column, 1)

    def _configure_shared_widgets(self):
        w = self.window
        for table in (w.tableView, w.tableView_2):
            table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeMode.Stretch)
            table.horizontalHeader().setStretchLastSection(True)
            table.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        for editor in (w.textEdit_sf, w.textEdit_sf_2, w.textEdit_res, w.textEdit_res_2):
            editor.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)

        for page in (w.page, w.page_3):
            for label in page.findChildren(QLabel):
                font = label.font()
                point_size = font.pointSizeF()
                if point_size > 0:
                    font.setPointSizeF(point_size + 1.0)
                    label.setFont(font)

        for header in (w.label_33, w.label_34, w.label_49, w.label_50, w.label_52):
            font = header.font()
            font.setBold(True)
            header.setFont(font)

        section_groups = (
            w.groupBox_2,
            w.groupBox_3,
            w.groupBox,
            w.groupBox_run,
            w.groupBox_surface_review_titration,
            w.groupBox_4,
            w.groupBox_5,
            w.groupBox_6,
            w.groupBox_7,
            w.groupBox_8,
            w.groupBox_9,
            w.groupBox_run_2,
            w.groupBox_surface_review,
        )
        for group in section_groups:
            group.setStyleSheet("QGroupBox::title { font-size: 13pt; font-weight: 600; }")
